### ISSUE TITLE
Login error: AxiosError: Request failed with status code 429, reconnect in  120s.

### ISSUE THREAD

**Issue by stepo11** [grzegorz914/homebridge-melcloud-control#101]
Constantly getting error - Login error: AxiosError: Request failed with status code 429, reconnect in  120s.

Was working fine the other day. I have made no changes. I have tried 150 refresh instead of 120 and still nothing. I have updated to beta 2 and still nothing. 

Logs attached.
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14502011/homebridge.log.txt)

**Comment by grzegorz914** [comment]
Your account is locked, disable plugin for few hours and start again. If you have also other integrations then disable it too.

**Comment by stepo11** [comment]
Disabled it and re-enabled it. Different error now...

TypeError: Cannot read properties of undefined (reading '0')
    at MelCloudAtw.<anonymous> (/var/lib/homebridge/node_modules/homebridge-melcloud-control/src/deviceatw.js:315:50)
    at MelCloudAtw.emit (node:events:518:28)
    at MelCloudAtw.<anonymous> (/var/lib/homebridge/node_modules/homebridge-melcloud-control/src/melcloudatw.js:418:22)

**Comment by grzegorz914** [comment]
fixed
