### ISSUE TITLE
About 'disable auto mode' option

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#102]
About the option 'disable auto mode' of the plugin, it disables the auto mode of the device in Homekit / Home app or the 'auto' mode in the melcloud web interface? Thanks.

**Comment by grzegorz914** [comment]
In home app

**Comment by peibol81** [comment]
Thank you for the quick answer.
But, when I activate this option, the 'automatic' function in the AC in the homekit home app continues as an selectable mode. Is this normal? What is the function of auto mode in this case? Thanks qgain:

**Comment by grzegorz914** [comment]
You can select what a mode will be used for Auto in plugin config, some users do not need auto but use fan or dry instead

**Comment by peibol81** [comment]
Thank you very much
