### ISSUE TITLE
Recomend update policy for the plugin

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#103]
What is the recommended strategy to update the plugin? Do you recommend updating each new version (0.18, 0.19...) or also the intermediate versions (0.19.1, 0.19.2...). For me, the essential thing is to have a stable system. Many users also think that if the version of the installed plugin works correctly it is better to never update, do you agree with this? Thank you

**Comment by grzegorz914** [comment]
Updates:
0.0.x  bug fixes
0.x.0 added new features, compatible with previous minor version
x.0.0  major changes which need interaction from user to working correct

**Comment by peibol81** [comment]
One more time, thanks.
I don't understand what do you say with x.0.0. There will be necessary reconfigure or add the AC device as new in version 1.0? Sorry, I don't understand.
When will arrive the 1.0 version? Are you eorking in this version?

**Comment by grzegorz914** [comment]
if change first numer of version 1.x.x o 2.x.x, mean that user need reconfigure some properties in plugin config again.
