### ISSUE TITLE
Docu change mqtt Set to State and vice versa

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#107]
I think in the docu the Publish -> SET  and Subscribe -> Info, State have to be change
<img width="772" alt="Bildschirmfoto 2024-03-14 um 21 59 14" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/24873682/6f8e60e3-1edf-458a-8b01-f8bf414d0059">

**Comment by grzegorz914** [comment]
i dont think so

**Comment by tobuser** [comment]
Maybe I'm making a thinking error. When I publish the following MQTT command: ha_melcloud_hse/Heat Pump/Ecodan/State {"OperationModeZone1":2}, nothing happens. But when I publish: hha_melcloud_hse/Heat Pump/Ecodan/Set {"OperationModeZone1":2}, after some time the new OperationModeZone1 value is set.

**Comment by grzegorz914** [comment]
All is correct here. Device itself publish “Info” and “State” and subscribe “Set”

**Comment by tobuser** [comment]
Okay that make sense. thanx
