### ISSUE TITLE
Not configured in MELcloud services

### ISSUE THREAD

**Issue by witchdrash** [grzegorz914/homebridge-melcloud-control#111]
Started getting this error with our air conditioners, I've tried removing the cached instance, deleting the plug in and reinstalling, yet the issue persists:

`[4/8/2024, 8:53:10 AM] [homebridge-melcloud-control] Air Conditioner, Bedfordshire AC, debug: Device Info: {
  "DeviceID": 41933758,
  "DeviceName": "Bedfordshire AC",
  "BuildingID": 307500,
  "BuildingName": null,
  "FloorID": 104796,
  "FloorName": null,
  "AreaID": 130860,
  "AreaName": null,
  "ImageID": 184286,
  "InstallationDate": "2022-05-01T00:00:00",
  "LastServiceDate": "2022-05-01T00:00:00",
  "Presets": [
    {
      "SetTemperature": 18,
      "Power": true,
      "OperationMode": 3,
      "VaneHorizontal": 12,
      "VaneVertical": 5,
      "FanSpeed": 3,
      "ID": 283877,
      "Client": 408808,
      "DeviceLocation": 41933758,
      "Number": 1,
      "Configuration": "<settings><st>18</st><pw>true</pw><om>3</om><vd>5</vd><hd>12</hd><fs>3</fs></settings>",
      "NumberDescription": "Standard Night"
    }
  ],
  "OwnerID": 408808,
  "OwnerName": null,
  "OwnerEmail": null,
  "AccessLevel": 4,
  "DirectAccess": false,
  "EndDate": "2500-01-01T00:00:00",
  "Zone1Name": null,
  "Zone2Name": null,
  "MinTemperature": 0,
  "MaxTemperature": 40,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "HideRoomTemperature": false,
  "HideSupplyTemperature": false,
  "HideOutdoorTemperature": false,
  "EstimateAtaEnergyProductionOptIn": false,
  "EstimateAtaEnergyProduction": false,
  "BuildingCountry": null,
  "OwnerCountry": null,
  "AdaptorType": 3,
  "LinkedDevice": null,
  "Type": 0,
  "MacAddress": "70:61:be:3a:5a:cf",
  "SerialNumber": "2145208029",
  "Device": {
    "PCycleActual": 0,
    "ErrorMessages": "",
    "DeviceType": 0,
    "CanCool": true,
    "CanHeat": true,
    "CanDry": true,
    "CanAuto": true,
    "HasAutomaticFanSpeed": true,
    "AirDirectionFunction": true,
    "SwingFunction": true,
    "NumberOfFanSpeeds": 5,
    "UseTemperatureA": true,
    "TemperatureIncrementOverride": 0,
    "TemperatureIncrement": 0.5,
    "MinTempCoolDry": 16,
    "MaxTempCoolDry": 31,
    "MinTempHeat": 10,
    "MaxTempHeat": 31,
    "MinTempAutomatic": 16,
    "MaxTempAutomatic": 31,
    "LegacyDevice": false,
    "UnitSupportsStandbyMode": true,
    "IsSplitSystem": false,
    "HasHalfDegreeIncrements": true,
    "HasOutdoorTemperature": true,
    "ModelIsAirCurtain": false,
    "ModelSupportsFanSpeed": true,
    "ModelSupportsAuto": true,
    "ModelSupportsHeat": true,
    "ModelSupportsDry": true,
    "ModelSupportsVaneVertical": true,
    "ModelSupportsVaneHorizontal": true,
    "ModelSupportsWideVane": false,
    "ModelDisableEnergyReport": false,
    "ModelSupportsStandbyMode": true,
    "ModelSupportsEnergyReporting": false,
    "ProhibitSetTemperature": false,
    "ProhibitOperationMode": false,
    "ProhibitPower": false,
    "Power": false,
    "RoomTemperature": 19,
    "OutdoorTemperature": null,
    "SetTemperature": 18,
    "ActualFanSpeed": 0,
    "FanSpeed": 4,
    "AutomaticFanSpeed": false,
    "VaneVerticalDirection": 7,
    "VaneVerticalSwing": true,
    "VaneHorizontalDirection": 12,
    "VaneHorizontalSwing": true,
    "OperationMode": 3,
    "EffectiveFlags": 0,
    "LastEffectiveFlags": 0,
    "InStandbyMode": false,
    "DemandPercentage": 100,
    "ConfiguredDemandPercentage": null,
    "HasDemandSideControl": false,
    "DefaultCoolingSetTemperature": 21,
    "DefaultHeatingSetTemperature": 23,
    "RoomTemperatureLabel": 0,
    "HeatingEnergyConsumedRate1": 0,
    "HeatingEnergyConsumedRate2": 0,
    "CoolingEnergyConsumedRate1": 0,
    "CoolingEnergyConsumedRate2": 0,
    "AutoEnergyConsumedRate1": 0,
    "AutoEnergyConsumedRate2": 0,
    "DryEnergyConsumedRate1": 0,
    "DryEnergyConsumedRate2": 0,
    "FanEnergyConsumedRate1": 0,
    "FanEnergyConsumedRate2": 0,
    "OtherEnergyConsumedRate1": 0,
    "OtherEnergyConsumedRate2": 0,
    "EstimateAtaEnergyProduction": false,
    "EstimateAtaEnergyProductionOptIn": false,
    "EstimateAtaEnergyProductionOptInTimestamp": null,
    "WeatherForecast": [],
    "HasEnergyConsumedMeter": true,
    "CurrentEnergyConsumed": 90100,
    "CurrentEnergyMode": 3,
    "CoolingDisabled": false,
    "EnergyCorrectionModel": null,
    "EnergyCorrectionActive": false,
    "MinPcycle": 1,
    "MaxPcycle": 1,
    "EffectivePCycle": 1,
    "MaxOutdoorUnits": 255,
    "MaxIndoorUnits": 255,
    "MaxTemperatureControlUnits": 0,
    "ModelCode": "0130",
    "DeviceID": 41933758,
    "MacAddress": "70:61:be:3a:5a:cf",
    "SerialNumber": "2145208029",
    "TimeZoneID": 118,
    "DiagnosticMode": 0,
    "DiagnosticEndDate": null,
    "ExpectedCommand": 1,
    "Owner": 408808,
    "DetectedCountry": null,
    "AdaptorType": 3,
    "FirmwareDeployment": null,
    "FirmwareUpdateAborted": false,
    "LinkedDevice": null,
    "WifiSignalStrength": -60,
    "WifiAdapterStatus": "NORMAL",
    "Position": "Unknown",
    "PCycle": 10,
    "PCycleConfigured": null,
    "RecordNumMax": 0,
    "LastTimeStamp": "2024-04-08T08:45:00",
    "ErrorCode": 8000,
    "HasError": false,
    "LastReset": "2022-11-16T11:14:56.632",
    "FlashWrites": 8,
    "Scene": null,
    "SSLExpirationDate": "2037-12-31T00:00:00",
    "SPTimeout": 1,
    "Passcode": null,
    "ServerCommunicationDisabled": false,
    "ConsecutiveUploadErrors": 0,
    "DoNotRespondAfter": null,
    "OwnerRoleAccessLevel": 1,
    "OwnerCountry": 237,
    "HideEnergyReport": false,
    "ExceptionHash": null,
    "ExceptionDate": null,
    "ExceptionCount": null,
    "Rate1StartTime": null,
    "Rate2StartTime": null,
    "ProtocolVersion": 0,
    "UnitVersion": 0,
    "FirmwareAppVersion": 37000,
    "FirmwareWebVersion": 0,
    "FirmwareWlanVersion": 0,
    "LinkToMELCloudHome": false,
    "LinkedByUserFromMELCloudHome": "00000000-0000-0000-0000-000000000000",
    "MqttFlags": 9,
    "HasErrorMessages": false,
    "HasZone2": false,
    "Offline": true,
    "SupportsHourlyEnergyReport": true,
    "Units": []
  },
  "DiagnosticMode": 0,
  "DiagnosticEndDate": null,
  "Location": 99569,
  "DetectedCountry": null,
  "Registrations": 50,
  "LocalIPAddress": null,
  "TimeZone": 118,
  "RegistReason": "STARTUP",
  "ExpectedCommand": 1,
  "RegistRetry": 0,
  "DateCreated": "2022-05-26T21:40:57.642Z",
  "FirmwareDeployment": null,
  "FirmwareUpdateAborted": false,
  "Permissions": {
    "CanSetOperationMode": true,
    "CanSetFanSpeed": true,
    "CanSetVaneDirection": true,
    "CanSetPower": true,
    "CanSetTemperatureIncrementOverride": true,
    "CanDisableLocalController": true,
    "CanSetDemandSideControl": false
  }
}
[4/8/2024, 8:53:10 AM] [homebridge-melcloud-control] Air Conditioner, Bedfordshire AC, Units are not configured in MELCloud service.`

**Comment by grzegorz914** [comment]
It's not an error, just info.  J
ust configure your device in MELCLoud service or just ignore it.

**Comment by grzegorz914** [comment]
its not a error, just info.

**Comment by witchdrash** [comment]
> its not a error, just info.

The units aren't in homebridge anymore, they're just gone

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by witchdrash** [comment]
I see each has to be added individually, ok that explains why they disappeared when I updated. How do I configure them in the melcloud service so I get rid of the error, it may not necessary, but it's putting a lot of junk into the log

**Comment by grzegorz914** [comment]
<img width="1291" alt="Zrzut ekranu 2024-04-8 o 11 34 54" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/37d852d6-0341-40fd-9a97-77b180e9fcf4">
<img width="1781" alt="Zrzut ekranu 2024-04-8 o 11 35 18" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/dd66eb86-4c4a-4217-b986-329a3a8ee008">

**Comment by witchdrash** [comment]
Thanks for your help I'll get that done, looks like my installer added the outdoor units the indoor
