### ISSUE TITLE
power consumption from a heatpump

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#112]
In the MELCLOUD app i can see the power consumption from the heatpump. Is there a way to get the power consumption from my heatpump with melcloud-control?

**Comment by grzegorz914** [comment]
Yes if you use External Integrations MQTT or RESTFul and extract the data from there for Your purpose. 
In Home app i don't see any practical use of this possibility.

**Comment by tobuser** [comment]
You are right. Foolish question
