### ISSUE TITLE
Target temperature changing arbitrarily

### ISSUE THREAD

**Issue by cars11** [grzegorz914/homebridge-melcloud-control#113]
For some reason this past week the temperature of my unit would change on its own. After I turn it on and set a temperature, it will increase itself after a short while. 
I’ve tried updating and restarting the plug-in to no avail

it doesn’t matter where I change it. Via Siri. Within the Home bridge interface, or directly via cloud. The plug-in increases the temperature after X Min every every time.

**Comment by grzegorz914** [comment]
Debug log please

**Comment by cars11** [comment]
Where do I find the debug log ?

**Comment by grzegorz914** [comment]
Enable in plugin settings Advanced Settings>>System>>Debug
