### ISSUE TITLE
No wifi in melcloud app

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#114]
Although I have access via ping to the network card of the air conditioner, the melcloud app tells me that the unifad cannot be updated and in the reports section, if I ask for a report of the strength of the wifi signal it tells me that there is no signal. But if I ping the internal ip, it does respond to me. I know this isn't a plugin problem but I'd like to know if this happens to anyone else (I hope it does and that it's a widespread problem)

**Comment by grzegorz914** [comment]
My be firewall lock

**Comment by peibol81** [comment]
No.IEl 20 abr 2024, a las 15:22, Grzegorz ***@***.***> escribió:﻿
My be firewall lock

**Comment by peibol81** [comment]
No. I reset the router and the problem persist.
I think is a problem with melcloud service.

**Comment by cars11** [comment]
Definitely a service issue. Lots of ppl having problems

**Comment by peibol81** [comment]
Thanks for the information. It's reassuringEl 21 abr 2024, a las 12:12, cars11 ***@***.***> escribió:﻿
Definitely a service issue. Lots of ppl having problems

**Comment by cars11** [comment]
https://community.home-assistant.io/t/melcloud-not-working/718920

**Comment by peibol81** [comment]
Thanks again.
The people is very frustrated with Mitsubishi, and is normal.
We still waiting...

Thank you for the link. Very usefull.

**Comment by peibol81** [comment]
It's interesting to take a look at the website you've passed by to see how things are going. Mitsubishi is not giving too much information and users are starting to get fed up and they are starting to speculate about the causes and possible 'homemade' solutions. It seems that this incidence is affecting the whole of Europe. Some speculate that it was a hack because this issue is taking a long time to resolve. Whatever it is, the only thing that is certain is that Mitsubishi is demonstrating a lot of shortcomings.

**Comment by cars11** [comment]
yeah im surprised there is no statement. usually they post when they have server maintenance or wahteve ri think

**Comment by peibol81** [comment]
Seems the problem is solved!
