### ISSUE TITLE
Temperature Mode "Automatic" between 20-24 degrees

### ISSUE THREAD

**Issue by DeReck16** [grzegorz914/homebridge-melcloud-control#115]
Hi folks, 

trying to get this to work, but the temparature range always jumps back to just one figure (say only 20 degrees) instead of 20-24 degress, no matter how often I set the range new. 

Is this because Melcloud is still not support this or I am doing something wrong here? 

Also as a side topic: I dont get the difference in control modes: Thermostat and Heater/Cool, is the only difference the Fan modes and the Swing? 

I am running a homekit automation where the room temparatue is taken from my Meross Thermostat and if the temarature is over 24 degrees I would like to cool down until it reaches 22 degrees. The automation triggers the cooling mode, but it does not stop when 22 degrees are reached. Any tips for that, too? Thanks!

**Comment by grzegorz914** [comment]
The heating/cooling threshold is hard coded in AC device, so we can not change it. We can only set the mode and report  current set temp. 

Difference between thermostat and heather cooler is  that what you described and additionally some difference in report current modes.

You need create automation to stop cooling if the 22 degrees are reached, but this function is implemented in AC device in automatic Mode.

**Comment by grzegorz914** [comment]
Auto Mode
![IMG_1831](https://github.com/user-attachments/assets/23a0b49e-cd89-48e5-8518-201016808033)
