### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by sacapo** [grzegorz914/homebridge-melcloud-control#116]
Hi there!
Not working for me from two out three days ago. I am both trying to reset homebridge and plugin and no success

any ideas? Thanks in advance

**Comment by sacapo** [comment]
![IMG_0013](https://github.com/grzegorz914/homebridge-melcloud-control/assets/9949104/1ebedc48-6dd6-4a5b-9e3e-0e2915f2a5b2)

**Comment by grzegorz914** [comment]
wrong credentials data, check email and password

**Comment by sacapo** [comment]
Thanks!

i did and no success. The weird thing is that I did not change my credentials and was working till few days ago.

**Comment by grzegorz914** [comment]
Can you log in direct from web browser?

**Comment by grzegorz914** [comment]
please enable debug mode and get the log

**Comment by sacapo** [comment]
> please enable debug mode and get the log

How can I share it?

**Comment by sacapo** [comment]
Just another thing. I have just realized it shows up in accessories and it works. The only problem is that the plugin does not appear on HomeKit

**Comment by grzegorz914** [comment]
You need to add it https://github.com/grzegorz914/homebridge-melcloud-control/wiki#adding-to-homekit

**Comment by sacapo** [comment]
Thanks, I’ll try and I’ll keep you posted!

**Comment by bjornand1** [comment]
The plugin has been working flawlessly for a very long time, but all of a sudden, the heat pump shows with "No response" in Apple Home. It is listed among the accessories, though, with the right temperature and status. As far as I know, I have changed nothing, so not sure how to get this working again? I have restarted the child bridge, but with no effect.

**Comment by grzegorz914** [comment]
Please remove it from home app and add it again
