### ISSUE TITLE
It is not an issues, it is a request Serial number and Model. 

### ISSUE THREAD

**Issue by marmitol** [grzegorz914/homebridge-melcloud-control#12]
Hi. It would be nice to have the serial number and model. If you can in a future version enable the serial number and model. Thank you very much.
![1D905C89-CB82-4EAF-884E-7E9B7FF55A2F](https://user-images.githubusercontent.com/61157812/180643896-15bd7067-6294-44b4-8aa6-352425856c8c.jpeg)

**Comment by grzegorz914** [comment]
What a version you use? it’s already there:
![5AD3E7CB-8BA1-4176-94E3-871D5FE0092D](https://user-images.githubusercontent.com/28867813/180645168-99681c00-10f6-4787-a64e-7b47eff7bfaf.png)
 
 If not display on your side please enable debug mode and get me the log.

**Comment by marmitol** [comment]
Hi. 

My version is: homebridge-melcloud-control v0.2.16

**Comment by grzegorz914** [comment]
Please enable debug mode in plugin settings and get the log.

**Comment by marmitol** [comment]
Hi, can you tell me the path to the log file so I can send it?
Thank you very much.

**Comment by grzegorz914** [comment]
Go to /var/lib/Homebridge/melcloud/ and get the files

**Comment by marmitol** [comment]
Hello.
Yesterday I activated Debug.
![image](https://user-images.githubusercontent.com/61157812/181453871-009cb910-8ec7-4ca5-b0c1-59659d0eb8c7.png)
The files in the folder you have indicated.
![image](https://user-images.githubusercontent.com/61157812/181454201-689c4d08-124f-4274-8941-0c629f639af2.png)
Attached to the file, data that may be sensitive has been masked with "***********"
[Casa_Buildings.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/9206923/Casa_Buildings.txt)

**Comment by grzegorz914** [comment]
Hi, 
Here in api is not any device reported and is present as undefined:
 `"Units": []`

if you get me your device Model Name for example("MSZ-LN18VG2(W/V/R/B)") and  ModelCode from api then I can create models data base and present it basis on ModelCodes.
`"ModelCode": "0**0"`

**Comment by marmitol** [comment]
Hi.

MODEL PEAD-M71JA2

**Comment by grzegorz914** [comment]
what is the BodelCode from api, look into this _buildings file

**Comment by marmitol** [comment]
Sorry 
ModelCode: "0130"

**Comment by grzegorz914** [comment]
Look like this is WLAN model code not the device itself because is same as mine. Are you proper configured the device on MELCloud, the model need to be in `"Units": []`
![Zrzut ekranu 2022-07-28 o 12 28 47](https://user-images.githubusercontent.com/28867813/181484681-04041c2b-7553-42c5-b86f-7d09441e037a.png)

**Comment by grzegorz914** [comment]
You can try 0.3.0 beta, added the serialNumber from WLAN adapter to display in Homa.app

**Comment by marmitol** [comment]
Hello,
The information was blank.
I have already modified it.
![image](https://user-images.githubusercontent.com/61157812/181486717-93258e11-fd35-4910-8a0d-aec388eadd1e.png)
![image](https://user-images.githubusercontent.com/61157812/181487095-a376f9d6-8cf5-431f-9544-bb42f6291adc.png)
Thank you very much.
