### ISSUE TITLE
What happens with homekit automations

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#122]
I have a lot of automations related with the melcloud unit. I think that I delete it from Homekit i will loose a lot of automations. Is posible avoud this?

**Comment by grzegorz914** [comment]
You need to add device to automations again. I think is not difficult.

**Comment by peibol81** [comment]
Difficult no, but boring and large, yes. In my case I have automations and shorcuts with conditions like 'if open a window, shut down the AC', or inverse 'if the AC is on and open window, first notify and after 30 seconds shut down the AC'. And I have 5 windows... And add scenes and automations when I exit home... At least 40 automations and scenes.. Boring 😔 In verIonn 1.0 I don't see motivation to upgrade, maybe I'll wait to future updates with new features. The last 0.x version works great

**Comment by grzegorz914** [comment]
If you don’t want run duplicated devices then stay by 0.21.x, In 1.0.0 is only one breaking change.

**Comment by peibol81** [comment]
Ok. Thanks. Is not difficult but for me is a lot of job. And I'm blind and is a slowly job for me. Can I first add the new unit and later delete the old? If it is possible, I think is a possible solution. If I remake the scenes wiyh the new unit before delete the old,the scenes and automation will no automatically deleted. The problem occurs when a scekne is empty or an automation no has a valid condition to start (a dispositive than no rxist)

**Comment by grzegorz914** [comment]
Yes, you can first add the new device and later delete the old not responsible.

**Comment by peibol81** [comment]
That's good news, it makes it a little easier for me when I decide to update. I suppose that the big change from 0.x to 1.x means that in your roadmap you have planned to add new options and features that will represent an important leap forward and that the publication of version 1.0 is only the first step of what is to come. I will be attentive because right now I need important improvements that encourage me to update. I can also tell you that the plugin in its latest version 0.x has reached an excellent level of excellence. It works perfectly and I use it (and enjoy it) every day. I congratulate you on a perfect job. Right now it is very difficult for me to think about how to improve the plugin from now on, so I will be very attentive.

**Comment by grzegorz914** [comment]
Its changed version to 1.0.0 because its break previous paired devices.

**Comment by peibol81** [comment]
I know, you say to me a few weeks ago, that any major change (0.x, 1.x...) suposes always delete and connect to home app again the unit.
