### ISSUE TITLE
Version 1.0 don't appears in homebridge-ui-x

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#123]
I don't know if its normal, but in the homebridge web interface don't appears the new update of the melcloud plugin to 1.x.

**Comment by mpopof** [comment]
I had the same issue, uninstalled the previous version and then installed and configured the new one. You will have to remove and re add the devices anyway .

Just make sure that you have the Homebridge UI updated to the latest version which is 4.56.4 installed

**Comment by grzegorz914** [comment]
Update the HB UI to 4.56.4 or above
