### ISSUE TITLE
No connection after the last 2 updates

### ISSUE THREAD

**Issue by JornDL** [grzegorz914/homebridge-melcloud-control#124]
Hi

I have no connection after the last 2 update to iOS Home.

I can still use the dedicated iOS app - "Melcloud" with out any issues.

I this an error added with one of the 2 latest updates of the plugin ?

**Comment by grzegorz914** [comment]
What a error? Any log

**Comment by JornDL** [comment]
Hi

I was not aware that I had to reconnect it to Apple Homekit.

I did that and now it's working.

Have a nice weekend :-)
