### ISSUE TITLE
It was all well, until it wasn't

### ISSUE THREAD

**Issue by pmahli** [grzegorz914/homebridge-melcloud-control#125]
Suddenly I get the following error and see no change in getting of it. 

[melcloudcontrol] Account info@ahlers.at, Connect to MELCloud error: AxiosError: Request failed with status code 500, reconnect in  120s.

Any solution proposals?

**Comment by grzegorz914** [comment]
Looks like internal MELCloud server problem

**Comment by pmahli** [comment]
Thx! So others should have the issue as well, right?

**Comment by grzegorz914** [comment]
On my dude is same error, as I know the MELCloud server is under maintenance

**Comment by pmahli** [comment]
A beer for you!! Thx, mate.
