### ISSUE TITLE
Hide external temperature sensor 

### ISSUE THREAD

**Issue by adamkylegreen** [grzegorz914/homebridge-melcloud-control#126]
Is it possible to hide the external temperature sensor from HomeKit?

**Comment by grzegorz914** [comment]
For Heat Pump?, why You want to hide it?

**Comment by adamkylegreen** [comment]
Because when you ask Siri what temp the room is, it says ranges from 20 degrees to 25 degrees. Also with 3 sensors it doesn’t group all devices into one so to change the fan speed you have to click into the group, then click on the device, then fan speed rather than just clicking on one.

**Comment by grzegorz914** [comment]
You took about AC, Heat Pump or ERV, because i don’t understand what you want to do. In AC and ERV device the fan speed can be changed direct from Heather/Cooler or Thermostat settings.

**Comment by adamkylegreen** [comment]
Aircon. 

Since the addition of the heat pump temp sensor, HomeKit creates a group for the 3 accessories instead of 1. So to change the fan speed now, I have to go into HomeKit > aircon (group) > settings cog > accessories > shows 3 items (2 temp sensors and aircon) > aircon > settings cog > fan speed. 

Before that I could just select Aircon bedroom (no group) > settings cog > fan speed. 

There doesn’t appear to be a way to ungroup the 2 temperature sensors from the aircon group so I don’t have to do this each time. 
Also when asking Siri what temperature the room is, she thinks we’re talking about the group of devices (aircon + outside), rather than the aircon unit temp individually. 

So I guess what I’m asking is whether we can ungroup the accessories or hide the heat pump sensor altogether?

**Comment by adamkylegreen** [comment]
https://github.com/user-attachments/assets/7a4ce438-ed19-46d1-a962-f71506e2cbb0

**Comment by grzegorz914** [comment]
Ok, i will look info this and add possibility to enable/disable every sensor separately

**Comment by grzegorz914** [comment]
added in v1.1.0
