### ISSUE TITLE
Failed to connect to devices (not reachable)

### ISSUE THREAD

**Issue by samoht0403** [grzegorz914/homebridge-melcloud-control#128]
Dear all,

yesterday I realized that my air conditioners are no more reachable. If I try to identify them I got the message that it failed, so I cannot control them.

Identifying the bridge works.

Setup:
* homebridge 1.8.4
* melcloud 1.0.7
* node-js 20.12.2
* Eve app on iPhone 12, newest iOS.

Anyone's got an idea or the same problem?

Thanks in advance,
Thomas

**Comment by grzegorz914** [comment]
What is in the log?

**Comment by samoht0403** [comment]
Here it is, nothing special in my eyes
[homebridge.log](https://github.com/user-attachments/files/16324013/homebridge.log)

**Comment by grzegorz914** [comment]
Hm, all is correct in the log, can You control it direct from Homebridge UI?

**Comment by samoht0403** [comment]
Thanks for your reply. Yes, I can control it (probably "unfortunately")

**Comment by grzegorz914** [comment]
Try this https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by samoht0403** [comment]
Thank you. Fixed it. Regards!
