### ISSUE TITLE
Automations AC unit

### ISSUE THREAD

**Issue by jammmyb** [grzegorz914/homebridge-melcloud-control#129]
Hi!

Plugin installed without a hitch and controls working in Apple Home. 

The oddities are automations. 

I set the AC to switch off at 11:55pm under automations. 

I woke up at 2am, it’s still on. 

Next night, the AC was not used so was switched off. 

I wake up at 3am and the AC is switched on. 

Apple Home knows the state of the AC. Why would it switch it on?

Why can’t it switch it off?

**Comment by grzegorz914** [comment]
Check your HomeKit automations settings first. In my case simply ON/OFF based on state of security system all working OK.

**Comment by grzegorz914** [comment]
@jammmyb  
are you fix this on your side, if no You need to enable debug mode and post it after this event happens. Right now I close the because I see this as no plugin issue.
