### ISSUE TITLE
V0.21.8

### ISSUE THREAD

**Issue by Cameleon4** [grzegorz914/homebridge-melcloud-control#130]
Hello, since V0.21.8 it's impossible to do updates.
When I switch to a new version, my air conditioning is unresponsive in HomeKit. Where could the problem be coming from? Thank you for your help.

**Comment by grzegorz914** [comment]
Are you read changelog before update: https://github.com/grzegorz914/homebridge-melcloud-control/blob/main/CHANGELOG.md#important-changes-v100-and-above

**Comment by Cameleon4** [comment]
Merci
