### ISSUE TITLE
Illegal value of 70 degrees is reported

### ISSUE THREAD

**Issue by Patrick-999** [grzegorz914/homebridge-melcloud-control#131]
I get an error on each status update:

[homebridge-melcloud-control] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 70 exceeded maximum of 60. See https://homebridge.io/w/JtMGR for more info.

However, my heat pump does allow water to be 70 degrees.

**Comment by grzegorz914** [comment]
please post the debug log in plugin settings advanced settings>>>system>>debug enable it restart plugin and get the log

**Comment by Patrick-999** [comment]
[8/6/2024, 4:05:24 PM] [homebridge-melcloud-control] Heat Pump, Hus, debug: Account Info: {
  "ContextKey": "removed",
  "Client": "removed",
  "Terms": 1301,
  "AL": 1,
  "ML": 0,
  "CMI": true,
  "IsStaff": false,
  "CUTF": false,
  "CAA": false,
  "ReceiveCountryNotifications": false,
  "ReceiveAllNotifications": false,
  "CACA": false,
  "CAGA": false,
  "MaximumDevices": 10,
  "ShowDiagnostics": false,
  "Language": 18,
  "Country": 217,
  "RealClient": 0,
  "Name": "removed",
  "UseFahrenheit": false,
  "Duration": 525600,
  "Expiry": "2025-08-06T13:55:08.467",
  "CMSC": false,
  "PartnerApplicationVersion": null,
  "EmailSettingsReminderShown": true,
  "EmailUnitErrors": 0,
  "EmailCommsErrors": 0,
  "ChartSeriesHidden": 0,
  "DeletePending": false,
  "Throttle": true,
  "IsImpersonated": false,
  "LanguageCode": "sv",
  "CountryName": "Sverige",
  "CurrencySymbol": "kr",
  "SupportEmailAddress": "support@se.mee.com",
  "DateSeperator": "/",
  "TimeSeperator": ":",
  "AtwLogoFile": "ecodan_logo.png",
  "DECCReport": false,
  "CSVReport1min": false,
  "HidePresetPanel": false,
  "EmailSettingsReminderRequired": false,
  "TermsText": null,
  "MapView": false,
  "MapZoom": 21,
  "MapLongitude": "removed",
  "MapLatitude": "removed",
  "Throttled": false,
  "ClientId": "removed"
}
[8/6/2024, 4:05:24 PM] [homebridge-melcloud-control] Heat Pump, Hus, debug: Device Info: {
  "DeviceID": 116257407,
  "DeviceName": "Hus",
  "BuildingID": 814404,
  "BuildingName": null,
  "FloorID": null,
  "FloorName": null,
  "AreaID": null,
  "AreaName": null,
  "ImageID": -9,
  "InstallationDate": "2022-12-31T00:00:00",
  "LastServiceDate": "2022-12-31T00:00:00",
  "Presets": [],
  "OwnerID": 1048479,
  "OwnerName": null,
  "OwnerEmail": null,
  "AccessLevel": 4,
  "DirectAccess": false,
  "EndDate": "2500-01-01T00:00:00",
  "Zone1Name": null,
  "Zone2Name": null,
  "MinTemperature": 0,
  "MaxTemperature": 40,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "HideRoomTemperature": false,
  "HideSupplyTemperature": false,
  "HideOutdoorTemperature": false,
  "EstimateAtaEnergyProductionOptIn": false,
  "EstimateAtaEnergyProduction": false,
  "BuildingCountry": null,
  "OwnerCountry": null,
  "AdaptorType": 3,
  "LinkedDevice": null,
  "Type": 1,
  "MacAddress": "8c:53:e6:30:e5:7b",
  "SerialNumber": "removed",
  "Device": {
    "PCycleActual": 0,
    "ErrorMessages": "",
    "DeviceType": 1,
    "FTCVersion": 2600,
    "FTCRevision": "r0",
    "LastFTCVersion": 0,
    "LastFTCRevision": null,
    "FTCModel": 127,
    "RefridgerentAddress": 0,
    "SystemMaxFlowTemp": 0,
    "RefrigerantType": 0,
    "DipSwitch1": 0,
    "DipSwitch2": 0,
    "DipSwitch3": 0,
    "DipSwitch4": 0,
    "DipSwitch5": 0,
    "DipSwitch6": 0,
    "HasThermostatZone1": true,
    "HasThermostatZone2": true,
    "TemperatureIncrement": 0.5,
    "DefrostMode": 0,
    "HeatPumpFrequency": 0,
    "MaxSetTemperature": 50,
    "MinSetTemperature": 40,
    "RoomTemperatureZone1": 24,
    "RoomTemperatureZone2": -39,
    "OutdoorTemperature": 22,
    "FlowTemperature": 31,
    "FlowTemperatureZone1": 0,
    "FlowTemperatureZone2": 0,
    "FlowTemperatureBoiler": 0,
    "ReturnTemperature": 27,
    "ReturnTemperatureZone1": 0,
    "ReturnTemperatureZone2": 0,
    "ReturnTemperatureBoiler": 0,
    "BoilerStatus": false,
    "BoosterHeater1Status": false,
    "BoosterHeater2Status": false,
    "BoosterHeater2PlusStatus": false,
    "ImmersionHeaterStatus": false,
    "WaterPump1Status": false,
    "WaterPump2Status": false,
    "WaterPump3Status": false,
    "ValveStatus3Way": false,
    "ValveStatus2Way": false,
    "WaterPump4Status": false,
    "ValveStatus2Way2a": false,
    "ValveStatus2Way2b": false,
    "TankWaterTemperature": 60,
    "UnitStatus": 0,
    "HeatingFunctionEnabled": true,
    "ServerTimerEnabled": null,
    "ThermostatStatusZone1": false,
    "ThermostatStatusZone2": false,
    "ThermostatTypeZone1": 1,
    "ThermostatTypeZone2": 2,
    "MixingTankWaterTemperature": 0,
    "CondensingTemperature": 0,
    "DemandPercentage": 100,
    "ConfiguredDemandPercentage": null,
    "HasDemandSideControl": false,
    "DailyHeatingEnergyConsumed": 0.04,
    "DailyCoolingEnergyConsumed": 0,
    "DailyHotWaterEnergyConsumed": 2.01,
    "DailyHeatingEnergyProduced": 0.67,
    "DailyCoolingEnergyProduced": 0,
    "DailyHotWaterEnergyProduced": 4.95,
    "DailyLegionellaActivationCounter": 0,
    "LastLegionellaActivationTime": "0001-01-01T00:00:00",
    "EffectiveFlags": 0,
    "LastEffectiveFlags": 0,
    "Power": false,
    "EcoHotWater": false,
    "OperationMode": 0,
    "OperationModeZone1": 0,
    "OperationModeZone2": 2,
    "SetTemperatureZone1": 19,
    "SetTemperatureZone2": 20,
    "SetTankWaterTemperature": 70,
    "TargetHCTemperatureZone1": 19,
    "TargetHCTemperatureZone2": 35,
    "ForcedHotWaterMode": false,
    "HolidayMode": false,
    "ProhibitHotWater": false,
    "ProhibitHeatingZone1": true,
    "ProhibitHeatingZone2": true,
    "ProhibitCoolingZone1": false,
    "ProhibitCoolingZone2": false,
    "ServerTimerDesired": false,
    "SecondaryZoneHeatCurve": false,
    "SetHeatFlowTemperatureZone1": 0,
    "SetHeatFlowTemperatureZone2": 0,
    "SetCoolFlowTemperatureZone1": 0,
    "SetCoolFlowTemperatureZone2": 0,
    "DECCReport": false,
    "CSVReport1min": false,
    "Zone2Master": false,
    "DailyEnergyConsumedDate": "2024-08-05T00:00:00",
    "DailyEnergyProducedDate": "2024-08-05T00:00:00",
    "CurrentEnergyConsumed": 0,
    "CurrentEnergyProduced": 0,
    "CurrentEnergyMode": null,
    "HeatingEnergyConsumedRate1": 0,
    "HeatingEnergyConsumedRate2": 0,
    "CoolingEnergyConsumedRate1": 0,
    "CoolingEnergyConsumedRate2": 0,
    "HotWaterEnergyConsumedRate1": 0,
    "HotWaterEnergyConsumedRate2": 0,
    "HeatingEnergyProducedRate1": 0,
    "HeatingEnergyProducedRate2": 0,
    "CoolingEnergyProducedRate1": 0,
    "CoolingEnergyProducedRate2": 0,
    "HotWaterEnergyProducedRate1": 0,
    "HotWaterEnergyProducedRate2": 0,
    "ErrorCode2Digit": 0,
    "SpSubDivisionsToWrite": 0,
    "SpSubDivisionsToRead": 0,
    "SpState": 0,
    "SpSubDivisionsWriteInProgress": 0,
    "SpSubDivisionsReadInProgress": 0,
    "InitialSettingsData": null,
    "InitialSettingsTimestamp": null,
    "SupportsHourlyEnergyReport": false,
    "HasZone2": false,
    "HasSimplifiedZone2": false,
    "CanHeat": true,
    "CanCool": false,
    "HasHotWaterTank": true,
    "CanSetTankTemperature": true,
    "CanSetEcoHotWater": false,
    "HasEnergyConsumedMeter": true,
    "HasEnergyProducedMeter": true,
    "CanMeasureEnergyProduced": false,
    "CanMeasureEnergyConsumed": false,
    "Zone1InRoomMode": true,
    "Zone2InRoomMode": false,
    "Zone1InHeatMode": true,
    "Zone2InHeatMode": true,
    "Zone1InCoolMode": false,
    "Zone2InCoolMode": false,
    "AllowDualRoomTemperature": false,
    "IsGeodan": false,
    "HasEcoCuteSettings": true,
    "HasFTC45Settings": false,
    "HasFTC6Settings": false,
    "CanEstimateEnergyUsage": true,
    "CanUseRoomTemperatureCooling": false,
    "IsFtcModelSupported": true,
    "SystemMaxFlowTemperature": null,
    "MaxTankTemperature": 70,
    "IdleZone1": true,
    "IdleZone2": false,
    "MinPcycle": 1,
    "MaxPcycle": 1,
    "MaxOutdoorUnits": 255,
    "MaxIndoorUnits": 255,
    "MaxTemperatureControlUnits": 0,
    "ModelCode": "027a",
    "DeviceID": 116257407,
    "MacAddress": "8c:53:e6:30:e5:7b",
    "SerialNumber": "2422611007",
    "TimeZoneID": 119,
    "DiagnosticMode": 0,
    "DiagnosticEndDate": null,
    "ExpectedCommand": 1,
    "Owner": 1048479,
    "DetectedCountry": null,
    "AdaptorType": 3,
    "FirmwareDeployment": null,
    "FirmwareUpdateAborted": false,
    "LinkedDevice": null,
    "WifiSignalStrength": -54,
    "WifiAdapterStatus": "NORMAL",
    "Position": "Unknown",
    "PCycle": 2,
    "PCycleConfigured": null,
    "RecordNumMax": 1,
    "LastTimeStamp": "2024-08-06T16:04:00",
    "ErrorCode": 8000,
    "HasError": false,
    "LastReset": "2024-08-06T10:30:43.842",
    "FlashWrites": 1,
    "Scene": null,
    "TemperatureIncrementOverride": 0,
    "SSLExpirationDate": "2037-12-31T00:00:00",
    "SPTimeout": 1,
    "Passcode": null,
    "ServerCommunicationDisabled": false,
    "ConsecutiveUploadErrors": 0,
    "DoNotRespondAfter": null,
    "OwnerRoleAccessLevel": 1,
    "OwnerCountry": 217,
    "HideEnergyReport": false,
    "ExceptionHash": null,
    "ExceptionDate": null,
    "ExceptionCount": null,
    "Rate1StartTime": null,
    "Rate2StartTime": null,
    "ProtocolVersion": 0,
    "UnitVersion": 0,
    "FirmwareAppVersion": 37000,
    "FirmwareWebVersion": 0,
    "FirmwareWlanVersion": 0,
    "LinkToMELCloudHome": false,
    "LinkedByUserFromMELCloudHome": "00000000-0000-0000-0000-000000000000",
    "EffectivePCycle": 1,
    "MqttFlags": 9,
    "HasErrorMessages": false,
    "Offline": false,
    "Units": [
      {
        "ID": 1,
        "Device": 0,
        "SerialNumber": "removed",
        "ModelNumber": 555,
        "Model": "QUHZ-W40VA",
        "UnitType": 0,
        "IsIndoor": false
      },
      {
        "ID": 2,
        "Device": 0,
        "SerialNumber": "removed",
        "ModelNumber": 554,
        "Model": "EHPT20Q-VM2EA",
        "UnitType": 1,
        "IsIndoor": true
      }
    ]
  },
  "DiagnosticMode": 0,
  "DiagnosticEndDate": null,
  "Location": 23968,
  "DetectedCountry": null,
  "Registrations": 6,
  "LocalIPAddress": null,
  "TimeZone": 119,
  "RegistReason": "CONFIG",
  "ExpectedCommand": 1,
  "RegistRetry": 0,
  "DateCreated": "2024-08-06T10:30:23.715Z",
  "FirmwareDeployment": null,
  "FirmwareUpdateAborted": false,
  "Permissions": {
    "CanSetForcedHotWater": true,
    "CanSetOperationMode": true,
    "CanSetPower": true,
    "CanSetTankWaterTemperature": true,
    "CanSetEcoHotWater": false,
    "CanSetFlowTemperature": true,
    "CanSetTemperatureIncrementOverride": true
  }
}

**Comment by grzegorz914** [comment]
fixed in 1.1.3, your tank can be set to 70 degrees,
`"MaxTankTemperature": 70,`
