### ISSUE TITLE
Devices shown in HomeKit with - no response -

### ISSUE THREAD

**Issue by shaun72** [grzegorz914/homebridge-melcloud-control#134]
Updated tithe new homebridge version 1.8.4 incl the node 20.15.0. then updated tomelcloud v2.0.0.
All 3 elements are shown, but with „no response“ only.
Unable to activate or deactivate anything.
With the melcloud app, allis possible and working fine. Just to eliminate any access topics.

any idea? Any logs?

**Comment by mpopof** [comment]
Same here, had to revert to 1.1.5 and waited if someone else would had similar problem. I just noticed he had released new version 2.0.3 and it seems to work just fine with it.

**Comment by grzegorz914** [comment]
In 2.0.0 was breaking changes in config, restful and mqtt. After update need to open settings and just save it again then restart the plugin. In change log was described that changes in config need to be adapted.

**Comment by grzegorz914** [comment]
### After update to v2.0.0 RESTFull and MQTT config settings need to be updated

**Comment by grzegorz914** [comment]
Right now I pulled back the 2.0.0, 2.0.1, and 2.0.2. 2.0.3 container workaround for this which not adapted own settings and get error in log.
