### ISSUE TITLE
V 2 time to life

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#135]
The version 1 was a very short time to life.

**Comment by grzegorz914** [comment]
What you mean

**Comment by peibol81** [comment]
What is the time of live expected of the version 2?

**Comment by grzegorz914** [comment]
Who knows.

**Comment by peibol81** [comment]
Each version change means having to delete the device and reconfigure it. If you have environments, shortcuts and automations as in my case, it is a big problem because it costs a lot to leave the configuration as it was before. I commented on this because the change to version 1.0 has been a little disappointing, because of how little it has lasted. If you now have to repeat the whole process with version 2.0, at least I would like to know if the lifetime is expected to be longer than version 1.0. I hope you have understood me. Thank you

**Comment by grzegorz914** [comment]
Only update to v1 need to remove and add devices to home kit again, v2 just changes properties in config for MQTT and RESTFul all other still working as before. All shortcuts and automations will not be deleted. If devices need to be deleted and added again then this is described in changelog.

**Comment by peibol81** [comment]
P still inv 0. I cann update to v 2 without reconfigure nothing?

**Comment by grzegorz914** [comment]
Yes, update direct to 2.2.2

**Comment by grzegorz914** [comment]
Update from v0 to v1, v2, vx need remove and add the devices to the HomeKit again.

**Comment by peibol81** [comment]
If I have to remove the device and reconfigure it, for me it is a complicated process because I am blind and it takes me a lot of time and a lot of problems. Losing the scenes and automations are a real headache for me, so although I would like to try version 2.0, if it is necessary to do all that process I will continue in the Zero version. X, which at the moment works very well for me. Thank you for everything

**Comment by grzegorz914** [comment]
To make backup of HomeKit and store all scenes and automations you can use Controller app.

**Comment by peibol81** [comment]
I know that application and also its backup function. But in reality that does not solve anything, because if you have to delete the device and reconfigure it, you also have to reconfigure the scenes and environments, and there the backup, does not solve anything. It can help to recover an old scene or shortcut, but you still have to reconfigure it with the new device. For me, because of my disability, that action costs me a lot. I use VoiceOver and in the end I get it, but it's very, very slow and very tedious for me. I appreciate all the information but as long as the zero version continues to work well, I will continue with it. Thanks a lot
