### ISSUE TITLE
Account Error on Login

### ISSUE THREAD

**Issue by WolfmanT** [grzegorz914/homebridge-melcloud-control#136]
Since today i get an error form the plugin on start:
 Connect to MELCloud error: TypeError: log.success is not a function., check again in: 120s
Yesterday it worked fine, i have updated to the newest version.

**Comment by grzegorz914** [comment]
Try to install Homebridge 2.0 beta

**Comment by WolfmanT** [comment]
But it worked till yesterday! The only thing i changed was the version of the plugin. I tried to get back to an older version with no success

**Comment by grzegorz914** [comment]
Yes, this new version require HB 2.0 to working correct, just update it or instal 2.1.0 plugin version

**Comment by WolfmanT** [comment]
Ah, thank you! It worked after downgrading to the first 2.xxxx Version...;-)

**Comment by grzegorz914** [comment]
You can update to 2.3.3 which is again compatible with HB 1.8.x
