### ISSUE TITLE
Device state error

### ISSUE THREAD

**Issue by mlamieri** [grzegorz914/homebridge-melcloud-control#14]
Dear grzegorz914,

thanks for developing this wonderful plugin. I am opening this issue because I obtain the following error when the plug-in try to setup the Air Conditioner model MSZ-SF42VE3.

Check device state error: TypeError: Cannot read properties of null (reading 'toString')

I attach the relevant snippet of the log with debug information. Let me know if you need additional details to address the issue.

[melcloud_error.txt.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/9224785/melcloud_error.txt.txt)

Thanks for your support and best regards,
Marco

**Comment by grzegorz914** [comment]
fixed in 0.2.17

**Comment by mlamieri** [comment]
Thanks!
