### ISSUE TITLE
Problem adding device in version 3.0.6

### ISSUE THREAD

**Issue by Kirshley1** [grzegorz914/homebridge-melcloud-control#140]
Hello! I just updated to the latest version (3.0.6) and the device appears in Homekit as "no response". In the accessories in homebridge it has disappeared. I have reviewed the notes of this latest version and it says that you have to configure it from the homebridge ui x, and not manually. I can't find a way to add the device from the homebridge ui X. Can you help me?

**Comment by grzegorz914** [comment]
![IMG_1010](https://github.com/user-attachments/assets/b203c07a-5702-473f-906e-f7dc8b13b7cd)

**Comment by Kirshley1** [comment]
Before I did that and the air conditioning was detected but it was not added to the accessories. Now with the new version 3.0.8 that has been published it already works for me and adds it well to my accessories. What I notice now is that it takes longer to change state in homekit when going from cold to hot and vice versa.
Thanks for your help!

**Comment by grzegorz914** [comment]
In version before 3.0.8 the devices by default was disabled in plugin config, after add it need to go to config menu and enable it first. In 3.0.8 by default are enabled.
