### ISSUE TITLE
Lost split since last update 

### ISSUE THREAD

**Issue by AFLC7** [grzegorz914/homebridge-melcloud-control#141]
All my splits have been lost since the last update. Everything is OK on MELcloud side as the app responds perfectly. Do I have to reinstall everything, reprogram all my automations as I was always obliged to do due to bugs after every major update ? It’s a bit messy and boring isn’t it ?

**Comment by grzegorz914** [comment]
what you mean last update, from version to version?

**Comment by grzegorz914** [comment]
are You read Changelog and Important changes?

**Comment by AFLC7** [comment]
I upgraded from last version 2 to first version 3 and i applied version 3.1.0 today. I can’t use m’y splits via HomeKit. I don’t know about other things than HomeKit and my hoobs UI. Every part of my hoobs device is up to date. Of course I read documentation and I don’t know what you are talking about. It doesn’t work that’s my problem. Do I have to reinstall everything again and again ? I’m not keen in spending my days behind my keyboard ! You are hoobs certified that means everything should be seemless, in fact that’s not the case…AlexLe 31 août 2024 à 15:56, Grzegorz ***@***.***> a écrit :﻿
are You read Changelog and Important changes?

**Comment by grzegorz914** [comment]
No need to reinstall anything just go to plugin settings and Login to melcloud:
![IMG_1010](https://github.com/user-attachments/assets/8d2025a9-874b-43d9-844d-8c12b9479a1d)

**Comment by AFLC7** [comment]
Thank you I know how to log… bu the way this is my UI… reinstalling the bridge and losing again doesn’t solve the problem !

￼

**Comment by grzegorz914** [comment]
post please your config.json

**Comment by AFLC7** [comment]
Downgrading to 2.3.3 works, don’t care about crapy updates

**Comment by grzegorz914** [comment]
I think You don't enable devices in plugin config

**Comment by AFLC7** [comment]
My problem is that you released an update prior to hoops home bridge update to 2.0… Some people only want a stable platform not something that changes every week ! Polish bad work

**Comment by grzegorz914** [comment]
Ah You use HOOBS the platform for newbies, now I understand. Please post on HOOBS support forum if something not work.

**Comment by grzegorz914** [comment]
If you use native Homebridge and Config UI X which is much better as HOOBS then all will be working fine.

**Comment by AFLC7** [comment]
Polish arrogance calling me newbie… I understand why your product is so crapy…

**Comment by grzegorz914** [comment]
Every new update add new functionality and working Correct, all problems and issues are fixed constantly.
