### ISSUE TITLE
Still see odd behaviour when swiching modes

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#145]
I have the following mapping in the config

 "heatDryFanMode": 1,
"coolDryFanMode": 1,
"autoDryFanMode": 1,

However when I switch to another mode, it reverts back to the previous one (although is sending the proper command)

https://github.com/user-attachments/assets/7e28d88b-5e1d-4ba4-a80d-1caf973fbc9c

**Comment by grzegorz914** [comment]
Try 3.1.4.beta.0 and Łęt me know

**Comment by CyberMrProper** [comment]
Still happening, but I think I've found the root cause of this, when the devices refreshes itself in the background

`power` = true

When it refreshed due to the mode change

`power` = 1

line: https://github.com/grzegorz914/homebridge-melcloud-control/blob/0a38e9858d152d42199b6b12fb6283e4e4135321/src/deviceata.js#L222

so, later in the code, having a 1 in there skips the switch options completely 

https://github.com/grzegorz914/homebridge-melcloud-control/blob/0a38e9858d152d42199b6b12fb6283e4e4135321/src/deviceata.js#L256

**Comment by grzegorz914** [comment]
Power boolean value and is correct,  the switch react on true/false, Please enable debug modę innplugin config and post the log please

**Comment by CyberMrProper** [comment]
In javascript is not the same to have 1/0 or true/false

https://github.com/grzegorz914/homebridge-melcloud-control/blob/0a38e9858d152d42199b6b12fb6283e4e4135321/src/deviceata.js#L257

I tried adding in that line
```
case 1:
case true:
```

and it started working, also added in the log just to confirm this

`this.emit('warn',` `power: ${power}`);

when the device refreshed due to the pooling, it logs:
`power:` true

when the device refreshed due to the mode change, it logs:
`power:` 1

**Comment by grzegorz914** [comment]
Please use latest beta and please post the debug log

**Comment by grzegorz914** [comment]
Ah ok I see where is the bug, will update it today later and let You to test

**Comment by CyberMrProper** [comment]
Great!! Just let me know and I will test it out. Thanks for fixing this :)

**Comment by grzegorz914** [comment]
try beta 11

**Comment by CyberMrProper** [comment]
It's working like a charm. Thank you for your dedication on this.

**Comment by CyberMrProper** [comment]
After some more testing, I see some issues with the fan speed selector. It is not working properly, I will open a new issue if you prefer.

**Comment by grzegorz914** [comment]
Yes please open new issue
