### ISSUE TITLE
Just updated to 3.1.3 and got "account.ataDevices is not iterable"

### ISSUE THREAD

**Issue by jaumebosch** [grzegorz914/homebridge-melcloud-control#146]
`[9/2/2024, 1:23:00 PM] [melcloudcontrol] Account Aire Acondicionado, Connect to MELCloud Success.
[9/2/2024, 1:23:00 PM] [melcloudcontrol] Account: Aire Acondicionado, MELCloud error: account.ataDevices is not iterable`

**Comment by grzegorz914** [comment]
Go to plugin settings and login in to MELCloud please

**Comment by jaumebosch** [comment]
thanks, never had to re-login in my previous updates.

**Comment by grzegorz914** [comment]
Fixed, Please update and try login again
