### ISSUE TITLE
Settings unavailable everywhere

### ISSUE THREAD

**Issue by Topione** [grzegorz914/homebridge-melcloud-control#148]
I don't understand why, but some functions are only available through a scene or automations, but not directly on the device on the main page.
![IMG_7046](https://github.com/user-attachments/assets/18a44a82-e270-4752-96bc-cb272ec0835a)
![IMG_7047](https://github.com/user-attachments/assets/ae3e25ad-14d1-4eb5-b0c4-28b4351a5a62)

**Comment by grzegorz914** [comment]
What you mean exactly?

**Comment by Topione** [comment]
The ability to control the fan speed and the swing are only visible through automations and scenes, not directly on the device on the main page of the Home app.

**Comment by grzegorz914** [comment]
If you press the gear button on the main page then open setting with swing and fan control. You can also create extra buttons in plugin settings to have direct control of this function.

**Comment by Topione** [comment]
Nothing when I press the settings icon. I know that I can create extra buttons, but I thought that I could have the same layout on the main page
![IMG_7048](https://github.com/user-attachments/assets/298c3ca9-820b-4b79-927a-73b3ab774ada)

**Comment by Topione** [comment]
Ohhhhh my bad, I found it. The main accessory is a group, and you have to select the second AC to find the sub-settings. My bad, everything is clear now
