### ISSUE TITLE
Fan speed selection exposure

### ISSUE THREAD

**Issue by normanmaurer** [grzegorz914/homebridge-melcloud-control#15]
Hi there...

thanks for this amazing project! One thing I was wondering is if it would be possible to "expose" the different Fan speed selection the same way as you expose the different modes for a AC. Basically not have 5 different buttons but just one "selection wheel". Is this possible ?

**Comment by grzegorz914** [comment]
This will be nice but is not possible, right now apple do not allow add two wheel services inside one accessory. In other thing if you set main mode as Heater/Cooler then you can select fan speed with slider in step 0 - off 1,2,3,4,5, Auto
![1F01DDDB-1FE2-4771-BAFE-4E1FC7F42FD6](https://user-images.githubusercontent.com/28867813/184936565-245134c2-3d0d-4eea-b235-2cd4cc415749.jpeg)

**Comment by normanmaurer** [comment]
Hmm I already use "Heater/Cooler" but don't see a slider at all:

<img width="739" alt="Screenshot 2022-08-17 at 09 45 57" src="https://user-images.githubusercontent.com/439362/185063968-16e4b15a-eff1-4b6d-8b69-a1eed271501c.png">

I am missing anything ?

**Comment by grzegorz914** [comment]
Can you post screenshot from your AC in HomeKit app? Pleas also enable debug mode In plugin config and get the log after restart it. What a version of plugin You use?

**Comment by normanmaurer** [comment]
@grzegorz914 never mind... restart fixed it 🤦

**Comment by grzegorz914** [comment]
nice
