### ISSUE TITLE
No response status when closing the accessory detail screen

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#151]
There is a small glitch that I don´t see in other home accessories. When I close to the accessory details screen, the aire conditioner goes for a second into a no responsive status.

https://github.com/user-attachments/assets/f174897a-34c8-4dbc-b740-61419b316f51

**Comment by grzegorz914** [comment]
This happen only if device is off, I don’t have any idea why?

**Comment by CyberMrProper** [comment]
Yes, only when it is off.

**Comment by CyberMrProper** [comment]
I see this happening also for radiators that I have, so this is a HK issue/behaviour.
