### ISSUE TITLE
Did finish launching error: account.ataDevices is not iterable

### ISSUE THREAD

**Issue by imTHAI** [grzegorz914/homebridge-melcloud-control#152]
Hello,

I don't know when it started (I believe since I did an upgrade of the plugin some days ago) I have in my logs:
[9/6/2024, 4:16:50 PM] [melcloudcontrol] Account imthai Connect to MELCloud Success.
[9/6/2024, 4:16:50 PM] [melcloudcontrol] Account: imthai, Did finish launching error: account.ataDevices is not iterable

On the Apple Home app all my aircon's are in status "not responding" and I can't manage them anymore.

Any idea about this problem ?

**Comment by polo2306** [comment]
Hello, the same for 1-2 days.

**Comment by imTHAI** [comment]
> Hello, the same for 1-2 days. I try preview version and it's the same..

Oh ok thanks, so I know it's not on my side, I can stop to search. 
(I thought something went wrong with my firewall. Then I also tried adding the plugin as a secondary hub. )

**Comment by imTHAI** [comment]
Ok I went back to the 3.1.7 and it works again. I'll wait for a fix.

By the way, it wasn't easy to know which version I had to downgrade to, because the proposed versions are different between the plugin and the ones listed in the Releases section on GitHub. There we have v3.1.2, 3.1.4, 3.1.8, and 3.1.9
and on the plugin: 
<img width="468" alt="image" src="https://github.com/user-attachments/assets/97edde93-caf8-4f0e-8f57-9083bfe207fc">

**Comment by polo2306** [comment]
Ok i try but doesn’t work. I’ll wait

**Comment by grzegorz914** [comment]
You do not need downgrade, just go to plugin settings and login to melcloud.

**Comment by polo2306** [comment]
It’s doesn’t work..

**Comment by imTHAI** [comment]
Well, now that it works again, I risked an upgrade and it still works. Strange because I'd like to specify that I had also checked that I was logged in.

**Comment by grzegorz914** [comment]
> It’s doesn’t work..

Post your config please.

**Comment by polo2306** [comment]
![image](https://github.com/user-attachments/assets/57162783-465f-473c-94c8-4fc5af22d84e)

when i reload my mel account, "objet" appear.

**Comment by grzegorz914** [comment]
Check your user and password, looks like are wrong

**Comment by polo2306** [comment]
No I try with MELCloud apps and it work..

**Comment by polo2306** [comment]
Ok sorry it works. I put the same password again and it work.. strange
