### ISSUE TITLE
Only one divice discoverable after upgrade to 3.1.11

### ISSUE THREAD

**Issue by mpopof** [grzegorz914/homebridge-melcloud-control#153]
After updating the plugin to the latest version the devices turned into no response. I removed the plugin and removed the devices from the Home App and installed it again finished the setup both AC's showed up in the Accessories tab in home bridge as they are configured in MelCloud, but when I try to add them to Home App only one of them appears. No matter what I have tried the AC in the living room does not appear in the app so I can add it.

I have tried to remove the child bridge in home app and re add it to no avail. I have tried to keep the plugin running with homebridge still the same. 
Tried to set a freshly configured plug in as a child bridge added to home app and still can only see one of the AC's but not the other.

Any suggestions? this is very frustrating as I have it running just fine and upgraded the plug in since I have fallen behind with a lot versions.

**Comment by mpopof** [comment]
![IMG_1011](https://github.com/user-attachments/assets/3802daf3-bee2-418e-8472-cf356718cc0d)
![IMG_1012](https://github.com/user-attachments/assets/32b21012-71fa-4d4f-a42d-9e1204ba404e)

**Comment by grzegorz914** [comment]
Go to plugin settings and login to melcloud

**Comment by mpopof** [comment]
![Screenshot from 2024-09-09 18-18-10](https://github.com/user-attachments/assets/0ed9917d-0a7c-46f3-9e8b-64698b2f00a1)
this is from when I  freshly installed the plugin last night.

![Screenshot from 2024-09-10 02-41-38](https://github.com/user-attachments/assets/38f93a9a-4352-4e6b-ad11-f5f15a17036d)
this is from now when I saw your comment.

I also enabled debugging logs that I will leave running for a bit

**Comment by mpopof** [comment]
[homebridge.log.txt](https://github.com/user-attachments/files/16940817/homebridge.log.txt)
For some reason when I get just the log from the plugin it comes emptry. so here it is the log from homebridge. 

I even went as further as removing homebridge from the Home app and added it again, but still only the Bedroom AC shows up when I try to add it, but both of them are appearing in the accessories tab of home bridge

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by mpopof** [comment]
After I used Unpair Single Bridge in Settings and removed all the associations with the AC that wont show up the problem is resolved thanks for all the help
