### ISSUE TITLE
Auto "Keep Between" temperatures resetting

### ISSUE THREAD

**Issue by markwwd** [grzegorz914/homebridge-melcloud-control#158]
If I set my AC to Auto and set it to keep the temps between 23-26c it resets to keep between 23-23c right after I close the accessory/home app.

**Comment by grzegorz914** [comment]
All is correct because MELCloud calculate temperature in AUTO mode internally, you need just set target temp nothing more.

**Comment by markwwd** [comment]
> All is correct because MELCloud calculate temperature in AUTO mode internally, you need just set target temp nothing more.

So this actually doesn't work?

**Comment by grzegorz914** [comment]
It’s work but is not possible set own lo and hi temp. This temp is hardcoded in MELCloud algorithm.
![Uploading IMG_1015.jpeg…]()

**Comment by grzegorz914** [comment]
![IMG_1015](https://github.com/user-attachments/assets/1440a318-bf7f-4da8-b60d-2aae75e22337)

**Comment by markwwd** [comment]
> It’s work but is not possible set own lo and hi temp. This temp is hardcoded in MELCloud algorithm.
> 
> 
> 
> 

That's too bad. Could you make the high temp setting rely on the temp. sensor?

For example, lo temp would be the actual set temp, hi temp would be "max. temp limit" if you know what I mean.

**Comment by grzegorz914** [comment]
Try 3.2.6-beta. Here I added in AUTO mode possibility to set lo and hi temp, let me know if this work.

**Comment by markwwd** [comment]
> Try 3.2.6-beta. Here I added in AUTO mode possibility to set lo and hi temp, let me know if this work.

Wow this seems to work.

If I set it to "KEEP BETWEEN 23-26c it sets the AC to 24c and it doesn't seem to reset it.

Great work!

**Comment by markwwd** [comment]
Though, if I change it to keep between 23-25c it doesn't adjust and leaves it at 24c like it was set before.

**Comment by grzegorz914** [comment]
the AUTO support is in progress install latest beta to get changes

**Comment by grzegorz914** [comment]
fixed
