### ISSUE TITLE
In version 3.3.4, settemperature stopped working 

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#162]

**Comment by CyberMrProper** [comment]
After upgrading to 3.3.4, setting cooling threshold temp is not being reflected in MELCloud app

**Comment by CyberMrProper** [comment]
Latest version is using default temperature property to set the cooling threshold. But on my AC that is not the right property to change it. As you see in the screenshot, target temp remains at 26, even if I change default temperature property to 23.

![IMG_3639](https://github.com/user-attachments/assets/79a8c6a6-345f-4673-ada6-eb2919d4180c)
![IMG_3638](https://github.com/user-attachments/assets/1d9c728f-4cf9-431a-9e4b-c9892c3a764e)
![IMG_3637](https://github.com/user-attachments/assets/0cf2340c-b06b-40ae-a91f-6c2dfbcdb6c3)

**Comment by grzegorz914** [comment]
try 3.3.5-beta.6 and let me know

**Comment by CyberMrProper** [comment]
Hi, I tried 3.3.7 beta 14 and is kind of broken, it says "Cooling to (null)" and when I go to the accessory detail it's empty
