### ISSUE TITLE
Latest update broke AUTO mode

### ISSUE THREAD

**Issue by markwwd** [grzegorz914/homebridge-melcloud-control#166]
The latest update broke the AUTO mode. When you set the AC to AUTO, it keeps resetting to KEEP BETWEEN 10-25c no matter what you set.

Version v3.3.12

**Comment by grzegorz914** [comment]
You can change only one wheel to set temp, the 10 will always  ack to 10. I have study the whole AUTO mode in Mitsubishi and we can not set lo and hi because this value are calculated internally based only on set temp.

**Comment by markwwd** [comment]
v3.3.11 works perfectly fine..

**Comment by grzegorz914** [comment]
Are You test it, set heat to 20 and cool to 25 in auto mode and check that correct work.

**Comment by markwwd** [comment]
Why don't you change the AUTO so it calculates the middle between LO and HI and then set the temperature in the middle?

For example:

KEEP BETWEEN 23 - 25C -> middle is 24C so set the temperature to 24C

or

KEEP BETWEEN 20 - 25C -> middle is 22.5C so set the temperature to that

This is the easiest and most convenient way..

**Comment by grzegorz914** [comment]
This is good idea, i will try to integrate it.

**Comment by grzegorz914** [comment]
try 3.3.13-beta and let me know

**Comment by markwwd** [comment]
This is now working very good!

![image](https://github.com/user-attachments/assets/fe2f7271-a5ca-49e1-9cd8-9f528fe06bc2)![image](https://github.com/user-attachments/assets/01657636-9d44-452c-8aaa-a4ec42e001e1)

**Comment by grzegorz914** [comment]
released 3.3.13

**Comment by markwwd** [comment]
Thanks! It's now behaving as it should. Awesome!
