### ISSUE TITLE
Full configuration accessory

### ISSUE THREAD

**Issue by Rochman78** [grzegorz914/homebridge-melcloud-control#169]
Hello,

I currently do not have access to the entire melcloud configuration, before I had the temperature sensors but now I have almost no choice of configuration can you please help me?

Have a nice day
<img width="714" alt="Capture d’écran 2024-10-04 à 11 00 44" src="https://github.com/user-attachments/assets/b14d0d78-9aaf-4a59-a9ce-558c7036ccfd">

**Comment by grzegorz914** [comment]
You need to log in to melcloud service on first screen after open plugin settings

**Comment by Rochman78** [comment]
it does the same thing to me
<img width="756" alt="Capture d’écran 2024-10-04 à 11 58 24" src="https://github.com/user-attachments/assets/7dbf1856-d4bd-4334-82f9-7913d4ecf682">
<img width="738" alt="Capture d’écran 2024-10-04 à 11 58 33" src="https://github.com/user-attachments/assets/4dd596de-e8ea-4891-9f3c-e4a4c968260d">

**Comment by grzegorz914** [comment]
Save and restart

**Comment by Rochman78** [comment]
it's always the same

**Comment by grzegorz914** [comment]
Please post your config

**Comment by Rochman78** [comment]
{
    "accounts": [
        {
            "name": "*********",
            "user": "*********",
            "passwd": "*********",
            "language": "7",
            "ataDevices": [
                {
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                },
                {
                    "id": 49899217,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Chambre",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": true,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "id": 350394,
                            "name": "Jour",
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "id": 364726,
                            "name": "Nuit",
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                },
                {
                    "id": 49898909,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Chambre amis",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "id": 364732,
                            "name": "Jour",
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "id": 364733,
                            "name": "Nuit",
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                },
                {
                    "id": 49848160,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Salon",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "id": 364727,
                            "name": "Jour",
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "id": 364729,
                            "name": "Nuit",
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                },
                {
                    "id": 49848977,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Salon Tv",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "id": 364730,
                            "name": "Jour",
                            "displayType": 0,
                            "namePrefix": false
                        },
                        {
                            "id": 364731,
                            "name": "Nuit",
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "atwDevices": [
                {
                    "displayMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorFlow": false,
                    "temperatureSensorReturn": false,
                    "temperatureSensorFlowZone1": false,
                    "temperatureSensorReturnZone1": false,
                    "temperatureSensorFlowWaterTank": false,
                    "temperatureSensorReturnWaterTank": false,
                    "temperatureSensorFlowZone2": false,
                    "temperatureSensorReturnZone2": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "ervDevices": [
                {
                    "displayMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "temperatureSensorSupply": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "refreshInterval": 120,
            "deviceRefreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        }
    ],
    "platform": "melcloudcontrol"
}

**Comment by grzegorz914** [comment]
all is correct in the config, are You use HOOBS, what a Config UI X version is installed? HB version?

**Comment by Rochman78** [comment]
<img width="738" alt="Capture d’écran 2024-10-04 à 13 42 59" src="https://github.com/user-attachments/assets/cde9713c-53a6-4729-acb6-03f5ffafed18">

**Comment by grzegorz914** [comment]
should display like this:
![Zrzut ekranu 2024-10-4 o 13 44 10](https://github.com/user-attachments/assets/8625f1da-eda3-47b6-a380-5199d1f2746c)

**Comment by grzegorz914** [comment]
![Zrzut ekranu 2024-10-4 o 13 44 10](https://github.com/user-attachments/assets/bea6a9db-afa0-4d11-be35-c0459056be3a)

**Comment by Rochman78** [comment]
The name is different of user ?
if that where is the name in melcloud ?

**Comment by Rochman78** [comment]
<img width="579" alt="Capture d’écran 2024-10-04 à 13 44 34" src="https://github.com/user-attachments/assets/af6238db-793c-4b15-9cbc-63e62c60dcf8">

**Comment by grzegorz914** [comment]
the name is irrelevant

**Comment by Rochman78** [comment]
yes before when i had the server on the mac it was like that i bought an orange pi zero and reinstalled hombridge on it and all the splugin and melcloud doesn't show it to me anymore

**Comment by grzegorz914** [comment]
As I understod, only the UI is not correct displayed but the plugin working correct? 
Arę You install all with this manual: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

**Comment by Rochman78** [comment]
Yes, the plugin works very well, but I don't have the interface for settings only.
The sd card was preflashered with Homebridge

**Comment by grzegorz914** [comment]
please post this problem as issue on the config ui x supports page, I don't have any idea why is not displayed correct on Your side. For sure try to downgrade config ui x to some older version

**Comment by Rochman78** [comment]
I've tried a lot of older versions but they don't solve the problem.
I'm going to post the problem on the hombridge UI page, for the moment do you think I can make the temperature sensors appear on homkit by setting True instead of false on the JS config? that's all I need for now.

**Comment by grzegorz914** [comment]
yes, set to true enable this sensor

**Comment by Rochman78** [comment]
ok thanks you very much for your help !!!
