### ISSUE TITLE
Air conditioning unit does not show up in Home app

### ISSUE THREAD

**Issue by punxsutawney** [grzegorz914/homebridge-melcloud-control#17]
First of all, thank you very much for this plugin, it's great to be able to control the air with the Home app. I have several air conditioners working, but one of them I can't add to Home app, it doesn't show up when I click on "I Don't Have a Code or Cannot Scan or More Options." I managed to get it to show up once at first, and it was working for a while but I had to delete the Homebridge and create another one and it seems that Home app thinks it already has it registered although it does NOT appear in the list of connected devices. This unit apears in melcloud plugin and can control it from there, BUT does not show up in Home app. Is it possible to trick Home app by changing the air conditioner identifier? How can I change the serial number or the Homebridge Instance Username of this particular device? Which one should I change? Thanks!

**Comment by grzegorz914** [comment]
Are You tryin this:
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by punxsutawney** [comment]
Sorry, no, but tried now and it works! thank you!
