### ISSUE TITLE
Lossnay Devices are not working

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#171]
After a fresh installation with V3 i get my ecodan heatpump the climate device but not the ERV Lossnay devices. 
[homebridge-melcloud-control.log (1).txt](https://github.com/user-attachments/files/17434867/homebridge-melcloud-control.log.1.txt)

**Comment by grzegorz914** [comment]
Fixed

**Comment by tobuser** [comment]
Very fast fix! It works. Thanx
