### ISSUE TITLE
ERR_REQUIRE_ESM: Incompatibility with Node.js 20+

### ISSUE THREAD

**Issue by EdgarKooren** [grzegorz914/homebridge-melcloud-control#180]
The plugin throws an `ERR_REQUIRE_ESM` error when running on Node.js v20+ (tested on v22.11.0). This happens because the plugin uses `require()` to load `@homebridge/plugin-ui-utils`, which is an ES Module. Node.js 20+ enforces strict ES Module support and no longer allows `require()` for ESM.

**Error:**  
```plaintext
[11/27/2024, 4:12:11 PM] [Homebridge UI] [homebridge-melcloud-control] /homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js:315
undefined
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /homebridge/node_modules/homebridge-melcloud-control/node_modules/@homebridge/plugin-ui-utils/dist/index.js from /homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js not supported.
Instead change the require of index.js in /homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js to a dynamic import() which is available in all CommonJS modules.
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js:3:52) {
  code: 'ERR_REQUIRE_ESM'
}
Node.js v22.11.0
```

**Steps to reproduce:**  
1. Run Homebridge with Node.js v22.11.0.
2. Install and configure the `homebridge-melcloud-control` plugin.
3. Observe the error in the logs.

**Expected Behavior:**  
The plugin should work without errors on Node.js 20+.

**Actual Behavior:**  
The plugin crashes due to an unsupported `require()` statement for ES Modules.

**Temporary Workaround:**  
Downgrading to Node.js v18 resolves the issue.

**Environment:**  
- **Homebridge:** vX.X.X (replace with your version)  
- **Plugin:** `homebridge-melcloud-control` vX.X.X (replace with your version)  
- **Node.js:** v22.11.0

**Comment by grzegorz914** [comment]
I have tested with node 22/23 and all working without any error

**Comment by skra72** [comment]
I have the same error since upgraded to v3.3.31. Literally due to this bug it is not possible to open the config UI anymore. You'll only get a spinning gear wheel. However, if the plugin was already configured it still works. You're just not able to configure it using homebridge-ui-x.

**Comment by grzegorz914** [comment]
Try to update config-up-x to 5.0 beta and let me know

**Comment by skra72** [comment]
Upgraded and still the same error.

Wonder how the upgrade should solve an ESM requirement?

**Comment by grzegorz914** [comment]
I can’t reproduce this issue on my side, all working correctly here.

**Comment by lolrenx** [comment]
getting the same error on a fresh install of homebridge
`Homebridge v1.8.5`

```
Node.js v20.12.2
[29/11/2024, 19:35:11] [Homebridge UI] [homebridge-melcloud-control] /var/lib/homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js:3
const { HomebridgePluginUiServer, RequestError } = require('@homebridge/plugin-ui-utils');
                                                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /var/lib/homebridge/node_modules/homebridge-melcloud-control/node_modules/@homebridge/plugin-ui-utils/dist/index.js from /var/lib/homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js not supported.
Instead change the require of index.js in /var/lib/homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-melcloud-control/homebridge-ui/server.js:3:52) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by grzegorz914** [comment]
My config right now is:
HB 2.0.0 beta 22
UI X 5.0.0 beta 17
Node.js 23.3 

all working as expected.

**Comment by lolrenx** [comment]
alright, let me upgrade to HB 2.0.0 beta 22 and report back

**Comment by lolrenx** [comment]
can I send you a PR to move from commonJS to ES modules ?

**Comment by grzegorz914** [comment]
Strange, I have no any problem on my side and can not reproduce this issue.
Yes, you can send PR.

**Comment by lolrenx** [comment]
Awesome thanks. The next tag should have this issue fixed 👍

**Comment by grzegorz914** [comment]
3.4.0 released, try and let me know

**Comment by skra72** [comment]
Awesome! Thanks!

**Comment by lolrenx** [comment]
all good, thank you @grzegorz914 !

**Comment by EdgarKooren** [comment]
Super fast fix, thnx @grzegorz914
