### ISSUE TITLE
Devices not showing up in plugin configuration UI

### ISSUE THREAD

**Issue by skra72** [grzegorz914/homebridge-melcloud-control#182]
Hi,

the plugin detects all 4 air conditioners correctly and they show up in the accessory overview of Homebridge.

<img width="300" alt="Screenshot 2024-12-02 at 16 36 44" src="https://github.com/user-attachments/assets/d6b2e241-e3b1-4de7-aaf2-36d568b46091">

But in the plugin's configuration screen none of them is shown, thus they cannot be configured.

<img width="300" alt="Screenshot 2024-12-02 at 16 43 16" src="https://github.com/user-attachments/assets/23d40108-adb4-4ef1-b8aa-cb79b91b0a30">

Any idea why the UI is not working?

Thanks!

**Comment by grzegorz914** [comment]
Press Connect to Melcloud

![IMG_1040](https://github.com/user-attachments/assets/19137830-deb3-4dc3-a496-5be05210c351)

**Comment by grzegorz914** [comment]
Post your config please

**Comment by skra72** [comment]
There you go:

`
{
    "accounts": [
        {
            "name": "s@k.c",
            "user": "s@k.c",
            "passwd": "***",
            "language": "4",
            "ataDevices": [
                {
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                },
                {
                    "id": 111227988,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Klima K1",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "SetTemperature": 24,
                            "Power": true,
                            "OperationMode": 3,
                            "VaneHorizontal": 3,
                            "VaneVertical": 5,
                            "FanSpeed": 0,
                            "ID": 618488,
                            "Client": 989498,
                            "DeviceLocation": 111227988,
                            "Number": 1,
                            "Configuration": "<settings><st>24</st><pw>true</pw><om>3</om><vd>5</vd><hd>3</hd><fs>0</fs></settings>",
                            "NumberDescription": "Voreinstellung 1",
                            "id": 618408,
                            "name": "Voreinstellung 1",
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": []
                },
                {
                    "id": 111218988,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Klima E1",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "SetTemperature": 24,
                            "Power": true,
                            "OperationMode": 3,
                            "VaneHorizontal": 3,
                            "VaneVertical": 3,
                            "FanSpeed": 0,
                            "ID": 618483,
                            "Client": 989488,
                            "DeviceLocation": 111218988,
                            "Number": 1,
                            "Configuration": "<settings><st>24</st><pw>true</pw><om>3</om><vd>3</vd><hd>3</hd><fs>0</fs></settings>",
                            "NumberDescription": "Voreinstellung 1",
                            "id": 618483,
                            "name": "Voreinstellung 1",
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": []
                },
                {
                    "id": 111227781,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Klima K2",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "SetTemperature": 24,
                            "Power": true,
                            "OperationMode": 3,
                            "VaneHorizontal": 2,
                            "VaneVertical": 2,
                            "FanSpeed": 0,
                            "ID": 618480,
                            "Client": 989488,
                            "DeviceLocation": 111227781,
                            "Number": 1,
                            "Configuration": "<settings><st>24</st><pw>true</pw><om>3</om><vd>2</vd><hd>2</hd><fs>0</fs></settings>",
                            "NumberDescription": "Voreinstellung 1",
                            "id": 618480,
                            "name": "Voreinstellung 1",
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": []
                },
                {
                    "id": 111227589,
                    "type": 0,
                    "typeString": "Air Conditioner",
                    "name": "Klima K3",
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "coolDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "SetTemperature": 24,
                            "Power": true,
                            "OperationMode": 3,
                            "VaneHorizontal": 1,
                            "VaneVertical": 5,
                            "FanSpeed": 0,
                            "ID": 618449,
                            "Client": 989488,
                            "DeviceLocation": 111227589,
                            "Number": 1,
                            "Configuration": "<settings><st>24</st><pw>true</pw><om>3</om><vd>5</vd><hd>1</hd><fs>0</fs></settings>",
                            "NumberDescription": "Voreinstellung 1",
                            "id": 618489,
                            "name": "Voreinstellung 1",
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": []
                }
            ],
            "atwDevices": [
                {
                    "displayMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorFlow": false,
                    "temperatureSensorReturn": false,
                    "temperatureSensorFlowZone1": false,
                    "temperatureSensorReturnZone1": false,
                    "temperatureSensorFlowWaterTank": false,
                    "temperatureSensorReturnWaterTank": false,
                    "temperatureSensorFlowZone2": false,
                    "temperatureSensorReturnZone2": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "ervDevices": [
                {
                    "displayMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "temperatureSensorSupply": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                }
            ],
            "refreshInterval": 120,
            "deviceRefreshInterval": 5,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        }
    ],
    "platform": "melcloudcontrol"
}
`

Thanks for your quick help.

**Comment by grzegorz914** [comment]
Strange, all correct in the config. Try to remove whole config then Connect to Melcloud again. I can not reproduce this on my side.

**Comment by skra72** [comment]
Ok. Setting up everything from scratch does not resolve the issue.

But I figured out where the problem in the configuration is: There is an empty ataDevice present at the beginning of the device array.

```
{
                    "displayMode": 1,
                    "heatDryFanMode": 1,
                    "autoDryFanMode": 1,
                    "temperatureSensor": false,
                    "temperatureSensorOutdoor": false,
                    "presets": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ],
                    "buttonsSensors": [
                        {
                            "displayType": 0,
                            "namePrefix": false
                        }
                    ]
                },
```

This gets added automatically when setting up a new account. If you delete it from the config, the UI works as expected.

And you can easily reproduce this by pressing the "Add" tab in the configuration dialog of the device section. As soon as you press this, all devices immediately disappear.

**Comment by skra72** [comment]
Work! Thanks!
