### ISSUE TITLE
Drying Mode

### ISSUE THREAD

**Issue by rockyss000** [grzegorz914/homebridge-melcloud-control#2]
hi, thank you for your work .... when will you implement dehumidifier mode (drying mode)?

**Comment by grzegorz914** [comment]
This coming soon, will be added as extra button for Dry, Fan, Purifying  and other Modes

**Comment by grzegorz914** [comment]
added in 0.0.9-beta.10, pleas test and let me know

**Comment by grzegorz914** [comment]
Added in 0.0.9.
