### ISSUE TITLE
Plugin not compatible with bridge mode in homekit

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#20]
When I switch the [child bridge](https://github.com/homebridge/homebridge/wiki/Child-Bridges) mode ON in my homebridge instance, the accessory is not being registered as part of the bridge. I think it remains as an external accessory instead of contained within the process. It would be great to make it compatible with this feature as I have several accessories and this improves performance.

**Comment by grzegorz914** [comment]
Will newer be a part of bridge, child bridge is always registered as independent accessory, this mode prevent crash whole Homebridge if something happens with the plug-in itself. This mode also get possibility to restart plugi without restart whole Homebridge. So all is working ok with my plugin.

**Comment by CyberMrProper** [comment]
Maybe I got confused since for other bridges the accessory appears as part of the bridge details. See screenshots: 
![835E2A2C-B72D-478E-AA66-C11D83792562_1_101_o](https://user-images.githubusercontent.com/63667331/193033764-0ed5787a-b4b6-47db-975f-223fd11cdd8b.jpeg)

![07D77C48-962A-4C00-B320-9B15FE4251DF_1_101_o](https://user-images.githubusercontent.com/63667331/193033769-844eb6e8-b838-4765-82d3-eaa7be0686f7.jpeg)

**Comment by grzegorz914** [comment]
The plug-in is registered as an external dynamic accessory, every device need to be paired manually. 
https://developers.homebridge.io/#/api/platform-plugins#apipublishexternalaccessories

Your Roborock is just normal platform or accessory direct.

**Comment by CyberMrProper** [comment]
Works as expected.
