### ISSUE TITLE
Heater cooler Auto mode threshold doesn't show correctly

### ISSUE THREAD

**Issue by ariwakio** [grzegorz914/homebridge-melcloud-control#21]
When I try to set a threshold ie. from 20c to 22c with Mitsubishi Heater Cooler (model LN-25) it briefly stick in Home app and then slides back to the last setting you touched. In the same time apparently it does stick in Homebridge logs:
Set cooling threshold temperature: 22°C
Set heating threshold temperature: 21°C

Can I do something so it would stick also in the home app?

**Comment by grzegorz914** [comment]
Mitsubishi do not get possibility to set Heater/Cooler Threshold right now. The plugin in Auto mode alway set target temperature instead threshold. Also MELCloud app do not offer this possibility.

**Comment by ariwakio** [comment]
Not a feature at this time, depends if Mitsubishi would add it as a feature.
