### ISSUE TITLE
mqtt - publish change state ("Power", true) Can't change the status on the client

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#22]
I enabled the mqtt function. When i publish {  "Power": true } i can see the that the status on the broker change to {  "Power": true }.  But a moment later the status go back to {  "Power": false }. So i can't switch the device. What can i do? Thank you

**Comment by grzegorz914** [comment]
At this moment we only publish state of the Device. Control device over MQTT is not implemented yet.

**Comment by tobuser** [comment]
Thanx for the info. Are there plans to implement this feature. Would be perfekt for Home Assistant user because the Melcloud integration for Home assistant ist by far not so good like your solution.

**Comment by grzegorz914** [comment]
Added in 0.19.0
