### ISSUE TITLE
Auto mode problem

### ISSUE THREAD

**Issue by GillesWi** [grzegorz914/homebridge-melcloud-control#23]
Hi!
I'm using 2x Mitsubishi Diamond Airco units and 1 outdoor unit. 

I noticed when using Siri the mode will sometimes automatically change to auto. How do you guys use this? Because auto mode doesn't seam to work. When changing the temperature in HomeKit it will automatically switch back. This is because melcloud doesn't allow a range (Like cool to '70' degrees and heat to '80' degrees) I think, right?

**Comment by grzegorz914** [comment]
Mitsubishi do not support set temperature for heating/cooling in Auto Mode separately. If you try to set temp for heating/cooling in auto mode will always send setTemperature only. I have 4xMSZ-LN A.C. Devices and all modes working correctly in my case. I do not tested this with Siri. Are you use Celsius or Fahrenheit? If possible please enable debug mode in plugin config and get the log during the changes.

**Comment by GillesWi** [comment]
Ok, got it! I saw a previous pull request about the auto/dry/fan... and other modes. Is there any way to prevent or remove the auto mode? I'm using Celsius. So I mostly use the command 'heat to 20 degrees', however sometimes it's in auto mode again when turning on.
Thank you for the help!

**Comment by grzegorz914** [comment]
@GillesWi still the issue exist with latest release.?

**Comment by grzegorz914** [comment]
fixed in v0.9.0
