### ISSUE TITLE
Air Conditioner XXXX , check state error, AxiosError: timeout of 10000ms exceeded, check again in 60s.

### ISSUE THREAD

**Issue by grunchy99** [grzegorz914/homebridge-melcloud-control#26]

**Comment by grzegorz914** [comment]
Its nothing bad, Just the MELCloud server doesn’t respond always.

**Comment by grunchy99** [comment]
Hi grzegorz914,

Thanks :-) Do you know url of melcoud servers ? Just one or many urls ?

**Comment by grzegorz914** [comment]
I know this one https://app.melcloud.com/Mitsubishi.Wifi.Client

**Comment by grunchy99** [comment]
Thanks :-)

**Comment by grunchy99** [comment]
I found this one with many request on my personal DNS : production.receiver.melcloud.com

**Comment by grzegorz914** [comment]
This is secure connection, right now not possible to use it.
