### ISSUE TITLE
Help with configuring JSON to display accessories in Homekit

### ISSUE THREAD

**Issue by ItsRubycub** [grzegorz914/homebridge-melcloud-control#27]
Hi,
I’m not familiar with programming Homebridge, it's new for me.
Here at home we got 5 Heater/Cooler-units connected to MELCloud and would like to use them though HomeKit with Homebridge.
I already followed the steps as given here: [https://github.com/grzegorz914/homebridge-melcloud-control](url) but don't know how ti configure the JSON-file in there.

I installed the MELCloud Control Plugin as written: 
<img width="1013" alt="Schermafbeelding 2023-01-22 om 18 36 29" src="https://user-images.githubusercontent.com/83958818/213930960-e927e0fa-31e4-4c8d-822e-bafecaca198c.png">

These are the Heater/Cooler-units that are showing up in the "accessories" tab in homebridge:
<img width="1017" alt="Schermafbeelding 2023-01-22 om 18 30 30" src="https://user-images.githubusercontent.com/83958818/213930958-9aa382d3-ca6d-4705-a79e-f8fc155f2955.png">

This is the code that already exists in the "configure" tab in homebridge (also see for the screenshot if not clear):
`{
    "bridge": {
        "name": "Homebridge FA32",
        "username": "deleted here for privacy reasons",
        "port": 51305,
        "pin": "deleted here for privacy reasons",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "HomeBridge",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "nl",
            "platform": "config"
        },
        {
            "accounts": [
                {
                    "name": "Ruben Melcloud",
                    "user": "deleted here for privacy reasons",
                    "passwd": "deleted here for privacy reasons",
                    "language": "12",
                    "ataDisplayMode": 0,
                    "ataPresets": false,
                    "atwDisplayMode": 0,
                    "atwPresets": false,
                    "ervDisplayMode": 0,
                    "ervPresets": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableDebugMode": false,
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false
                }
            ],
            "_bridge": {
                "username": "deleted here for privacy reasons",
                "port": deleted here for privacy reasons
            },
            "platform": "melcloudcontrol"
        }
    ]
}`
<img width="1020" alt="Schermafbeelding 2023-01-22 om 18 46 28" src="https://user-images.githubusercontent.com/83958818/213931503-cc7f1161-f97c-4451-b5d7-29f996dd6d8f.png">

This is the code that already exists in the "MELCloud Control" in the "plugin" tab in homebridge (also see for the screenshots if not clear):
`{
    "accounts": [
        {
            "name": "Ruben Melcloud",
            "user": "deleted here for privacy reasons",
            "passwd": "deleted here for privacy reasons",
            "language": "12",
            "ataDisplayMode": 0,
            "ataPresets": false,
            "atwDisplayMode": 0,
            "atwPresets": false,
            "ervDisplayMode": 0,
            "ervPresets": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "enableDebugMode": false,
            "enableMqtt": false,
            "mqttAuth": false,
            "mqttDebug": false
        }
    ],
    "_bridge": {
        "username": "deleted here for privacy reasons",
        "port": 37449
    },
    "platform": "melcloudcontrol"
}`
<img width="1014" alt="Schermafbeelding 2023-01-22 om 18 50 56" src="https://user-images.githubusercontent.com/83958818/213931684-14fd2f16-3277-4f21-a022-2f3e87fb9fe8.png">
<img width="1012" alt="Schermafbeelding 2023-01-22 om 18 51 03" src="https://user-images.githubusercontent.com/83958818/213931687-bb4583d7-7f27-49a6-9405-4a21623b3bb0.png">

Where do I put what code so the accessories show up in HomeKit-app?

Thanks in advance!
Ruben

**Comment by grzegorz914** [comment]
Why you not use GUI to configure it? In most cases you need only set user, passwd and language. Are you added this accessory to HomeKit after configured?  https://github.com/grzegorz914/homebridge-melcloud-control/wiki#adding-to-homekit

**Comment by ItsRubycub** [comment]
OMG I was looking over it, misunderstood it at the first glance. I feel so dumb to be honest.

Thanks for helping (so fast 🥇)!

Here's a glimp that it succeeded:
![image](https://user-images.githubusercontent.com/83958818/213933822-2d52b47a-fdd3-411c-b1c8-396af0060127.png)
![image](https://user-images.githubusercontent.com/83958818/213933805-b28596ab-481a-47d7-ab64-44908a47962c.png)

**Comment by grzegorz914** [comment]
Nice, Have fun.
