### ISSUE TITLE
characteristic value expected

### ISSUE THREAD

**Issue by Reliktdragons** [grzegorz914/homebridge-melcloud-control#30]
I get this in the Homebridge Log:

 [homebridge-melcloud-control] This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

Is this normal?

**Comment by grzegorz914** [comment]
no, its not normal, please enable debug mode in plugin settings advanced section and get the log.

**Comment by Reliktdragons** [comment]
since the reboot, the error has not yet occurred.
This is the current debug log:

 "Name": "Home",
    "AddressLine1": "",
    "AddressLine2": null,
    "City": "",
    "Postcode": ",
    "Latitude": 
    "Longitude": 
    "District": null,
    "FPDefined": false,
    "FPEnabled": false,
    "FPMinTemperature": 14,
    "FPMaxTemperature": 16,
    "HMDefined": false,
    "HMEnabled": false,
    "HMStartDate": null,
    "HMEndDate": null,
    "BuildingType": 1,
    "PropertyType": 8,
    "DateBuilt": null,
    "HasGasSupply": true,
    "LocationLookupDate": "2023-02-25T10:57:09.053",
    "Country": 85,
    "TimeZoneContinent": 3,
    "TimeZoneCity": 49,
    "TimeZone": 119,
    "Location": ,
    "CoolingDisabled": false,
    "Expanded": true,
    "Structure": {
      "Floors": [],
      "Areas": [],
      "Devices": [
        {
          "DeviceID": ,
          "DeviceName": "Home",
          "BuildingID": ,
          "BuildingName": null,
          "FloorID": null,
          "FloorName": null,
          "AreaID": null,
          "AreaName": null,
          "ImageID": -1,
          "InstallationDate": null,
          "LastServiceDate": null,
          "Presets": [],
          "OwnerID": 
          "OwnerName": null,
          "OwnerEmail": null,
          "AccessLevel": 4,
          "DirectAccess": false,
          "EndDate": "2500-01-01T00:00:00",
          "Zone1Name": null,
          "Zone2Name": null,
          "MinTemperature": 0,
          "MaxTemperature": 40,
          "HideVaneControls": false,
          "HideDryModeControl": false,
          "HideRoomTemperature": false,
          "HideSupplyTemperature": false,
          "HideOutdoorTemperature": false,
          "BuildingCountry": null,
          "OwnerCountry": null,
          "AdaptorType": 3,
          "LinkedDevice": null,
          "Type": 1,
          "MacAddress": "",
          "SerialNumber": "",
          "Device": {
            "PCycleActual": 0,
            "ErrorMessages": "",
            "DeviceType": 1,
            "FTCVersion": 1500,
            "FTCRevision": "r0",
            "LastFTCVersion": 0,
            "LastFTCRevision": null,
            "FTCModel": 2,
            "RefridgerentAddress": 0,
            "DipSwitch1": 182,
            "DipSwitch2": 160,
            "DipSwitch3": 16,
            "DipSwitch4": 0,
            "DipSwitch5": 0,
            "DipSwitch6": 0,
            "HasThermostatZone1": true,
            "HasThermostatZone2": true,
            "TemperatureIncrement": 0.5,
            "DefrostMode": 0,
            "HeatPumpFrequency": 0,
            "MaxSetTemperature": 40,
            "MinSetTemperature": 25,
            "RoomTemperatureZone1": 21,
            "RoomTemperatureZone2": -39,
            "OutdoorTemperature": 6,
            "FlowTemperature": 31.5,
            "FlowTemperatureZone1": 32,
            "FlowTemperatureZone2": 25,
            "FlowTemperatureBoiler": 25,
            "ReturnTemperature": 29.5,
            "ReturnTemperatureZone1": 26.5,
            "ReturnTemperatureZone2": 25,
            "ReturnTemperatureBoiler": 25,
            "BoilerStatus": false,
            "BoosterHeater1Status": false,
            "BoosterHeater2Status": false,
            "BoosterHeater2PlusStatus": false,
            "ImmersionHeaterStatus": false,
            "WaterPump1Status": false,
            "WaterPump2Status": false,
            "WaterPump3Status": false,
            "ValveStatus3Way": false,
            "ValveStatus2Way": false,
            "WaterPump4Status": false,
            "ValveStatus2Way2a": false,
            "ValveStatus2Way2b": false,
            "TankWaterTemperature": 39,
            "UnitStatus": 0,
            "HeatingFunctionEnabled": true,
            "ServerTimerEnabled": false,
            "ThermostatStatusZone1": false,
            "ThermostatStatusZone2": false,
            "ThermostatTypeZone1": 1,
            "ThermostatTypeZone2": 2,
            "MixingTankWaterTemperature": 0,
            "CondensingTemperature": 0,
            "DemandPercentage": 100,
            "ConfiguredDemandPercentage": null,
            "HasDemandSideControl": false,
            "DailyHeatingEnergyConsumed": 34.19,
            "DailyCoolingEnergyConsumed": 0,
            "DailyHotWaterEnergyConsumed": 2.12,
            "DailyHeatingEnergyProduced": 90.19,
            "DailyCoolingEnergyProduced": 0,
            "DailyHotWaterEnergyProduced": 4.87,
            "DailyLegionellaActivationCounter": 0,
            "LastLegionellaActivationTime": "0001-01-01T00:00:00",
            "EffectiveFlags": 0,
            "LastEffectiveFlags": 0,
            "Power": true,
            "EcoHotWater": true,
            "OperationMode": 0,
            "OperationModeZone1": 0,
            "OperationModeZone2": 2,
            "SetTemperatureZone1": 20,
            "SetTemperatureZone2": 20,
            "SetTankWaterTemperature": 45,
            "TargetHCTemperatureZone1": 20,
            "TargetHCTemperatureZone2": 35,
            "ForcedHotWaterMode": false,
            "HolidayMode": false,
            "ProhibitHotWater": false,
            "ProhibitHeatingZone1": false,
            "ProhibitHeatingZone2": false,
            "ProhibitCoolingZone1": false,
            "ProhibitCoolingZone2": false,
            "ServerTimerDesired": false,
            "SecondaryZoneHeatCurve": false,
            "SetHeatFlowTemperatureZone1": 25,
            "SetHeatFlowTemperatureZone2": 20,
            "SetCoolFlowTemperatureZone1": 20,
            "SetCoolFlowTemperatureZone2": 20,
            "DECCReport": false,
            "CSVReport1min": false,
            "Zone2Master": false,
            "DailyEnergyConsumedDate": "2023-02-27T00:00:00",
            "DailyEnergyProducedDate": "2023-02-27T00:00:00",
            "CurrentEnergyConsumed": 0,
            "CurrentEnergyProduced": 0,
            "CurrentEnergyMode": null,
            "HeatingEnergyConsumedRate1": 0,
            "HeatingEnergyConsumedRate2": 0,
            "CoolingEnergyConsumedRate1": 0,
            "CoolingEnergyConsumedRate2": 0,
            "HotWaterEnergyConsumedRate1": 0,
            "HotWaterEnergyConsumedRate2": 0,
            "HeatingEnergyProducedRate1": 0,
            "HeatingEnergyProducedRate2": 0,
            "CoolingEnergyProducedRate1": 0,
            "CoolingEnergyProducedRate2": 0,
            "HotWaterEnergyProducedRate1": 0,
            "HotWaterEnergyProducedRate2": 0,
            "ErrorCode2Digit": 0,
            "SpSubDivisionsToWrite": 0,
            "SpSubDivisionsToRead": 0,
            "SpState": 0,
            "SpSubDivisionsWriteInProgress": 0,
            "SpSubDivisionsReadInProgress": 0,
            "InitialSettingsData": null,
            "InitialSettingsTimestamp": null,
            "SupportsHourlyEnergyReport": false,
            "HasZone2": false,
            "HasSimplifiedZone2": false,
            "CanHeat": true,
            "CanCool": false,
            "HasHotWaterTank": true,
            "CanSetTankTemperature": true,
            "CanSetEcoHotWater": true,
            "HasEnergyConsumedMeter": true,
            "HasEnergyProducedMeter": true,
            "CanMeasureEnergyProduced": false,
            "CanMeasureEnergyConsumed": false,
            "Zone1InRoomMode": true,
            "Zone2InRoomMode": false,
            "Zone1InHeatMode": true,
            "Zone2InHeatMode": true,
            "Zone1InCoolMode": false,
            "Zone2InCoolMode": false,
            "AllowDualRoomTemperature": false,
            "IsGeodan": false,
            "HasEcoCuteSettings": false,
            "HasFTC45Settings": true,
            "HasFTC6Settings": false,
            "CanEstimateEnergyUsage": true,
            "CanUseRoomTemperatureCooling": false,
            "IsFtcModelSupported": true,
            "MaxTankTemperature": 60,
            "IdleZone1": true,
            "IdleZone2": true,
            "MinPcycle": 1,
            "MaxPcycle": 1,
            "MaxOutdoorUnits": 255,
            "MaxIndoorUnits": 255,
            "MaxTemperatureControlUnits": 0,
            "ModelCode": "027a",
            "DeviceID": ,
            "MacAddress": "",
            "SerialNumber": "",
            "TimeZoneID": 119,
            "DiagnosticMode": 0,
            "DiagnosticEndDate": null,
            "ExpectedCommand": 1,
            "Owner": 702010,
            "DetectedCountry": null,
            "AdaptorType": 3,
            "FirmwareDeployment": null,
            "FirmwareUpdateAborted": false,
            "LinkedDevice": null,
            "WifiSignalStrength": -65,
            "WifiAdapterStatus": "NORMAL",
            "Position": "Unknown",
            "PCycle": 2,
            "PCycleConfigured": null,
            "RecordNumMax": 1,
            "LastTimeStamp": "2023-02-28T17:22:00",
            "ErrorCode": 8000,
            "HasError": false,
            "LastReset": "2023-02-25T11:40:45.756",
            "FlashWrites": 2,
            "Scene": null,
            "TemperatureIncrementOverride": 0,
            "SSLExpirationDate": "2037-12-31T00:00:00",
            "SPTimeout": 1,
            "Passcode": null,
            "ServerCommunicationDisabled": false,
            "ConsecutiveUploadErrors": 0,
            "DoNotRespondAfter": null,
            "OwnerRoleAccessLevel": 1,
            "OwnerCountry": 85,
            "HideEnergyReport": false,
            "ExceptionHash": null,
            "ExceptionDate": null,
            "ExceptionCount": null,
            "Rate1StartTime": null,
            "Rate2StartTime": null,
            "ProtocolVersion": 0,
            "UnitVersion": 0,
            "FirmwareAppVersion": 37000,
            "FirmwareWebVersion": 0,
            "FirmwareWlanVersion": 0,
            "EffectivePCycle": 1,
            "MqttFlags": 9,
            "HasErrorMessages": false,
            "Offline": false,
            "Units": [
              {
                "ID": 1,
                "Device": 0,
                "SerialNumber": "",
                "ModelNumber": ,
                "Model": "EHSC-YM9C",
                "UnitType": 1,
                "IsIndoor": true
              }
            ]
          },
          "DiagnosticMode": 0,
          "DiagnosticEndDate": null,
          "Location": ,
          "DetectedCountry": null,
          "Registrations": 9,
          "LocalIPAddress": null,
          "TimeZone": 119,
          "RegistReason": "STARTUP",
          "ExpectedCommand": 1,
          "RegistRetry": 0,
          "DateCreated": "2023-02-25T10:54:21.3Z",
          "FirmwareDeployment": null,
          "FirmwareUpdateAborted": false,
          "Permissions": {
            "CanSetForcedHotWater": true,
            "CanSetOperationMode": true,
            "CanSetPower": true,
            "CanSetTankWaterTemperature": true,
            "CanSetEcoHotWater": false,
            "CanSetFlowTemperature": true,
            "CanSetTemperatureIncrementOverride": true
          }
        }
      ],
      "Clients": []
    },
    "AccessLevel": 4,
    "DirectAccess": true,
    "MinTemperature": 0,
    "MaxTemperature": 40,
    "Owner": null,
    "EndDate": "2500-01-01T00:00:00",
    "iDateBuilt": null,
