### ISSUE TITLE
Unit AC not reachable 

### ISSUE THREAD

**Issue by langluc** [grzegorz914/homebridge-melcloud-control#31]
Hello, for a few days one of the 4 air conditioners has not been reachable in homebridge. Instead from melcloud it is reachable.
![C8C3A72B-4F55-4C8C-B7FC-9CD9A351E8F7](https://user-images.githubusercontent.com/3002712/222242805-f23380f5-1ad7-4eea-9f48-8c03949396a9.png)

**Comment by grzegorz914** [comment]
Fixed
