### ISSUE TITLE
Heat Pump Zuhause, check info, ReferenceError: deviceListHistory24Formatters is not defined, check again in 60s.

### ISSUE THREAD

**Issue by Reliktdragons** [grzegorz914/homebridge-melcloud-control#33]
Issue with v0.8.1:

13/03/2023, 15:36:01] [homebridge-melcloud-control] Heat Pump Zuhause, check info, ReferenceError: deviceListHistory24Formatters is not defined, check again in 60s.

**Comment by grzegorz914** [comment]
fixed too
