### ISSUE TITLE
MQTT - will not connect

### ISSUE THREAD

**Issue by JornDL** [grzegorz914/homebridge-melcloud-control#34]
Hi

I'm trying to use MQTT with authorization log in, but connection is refused.

Could you please add the field "Client ID" to the MQTT authorization, please.

I'm using Mosquitto as my MQTT broker and it needs the "Client ID" to be abled to log in.

(great plugin - great work - happy with this)

**Comment by grzegorz914** [comment]
I have mosquito too and Connect co without any problem

**Comment by JornDL** [comment]
So what could be my issue ?
I have a lot of other MQTT clients - all using Client ID - but here I get this error:
[3/19/2023, 7:00:33 AM] [homebridge-melcloud-control] MQTT Connect error: Error: Connection refused: Not authorized

**Comment by grzegorz914** [comment]
wrong credentials

**Comment by grzegorz914** [comment]
Check user and password

**Comment by JornDL** [comment]
Just done that again to be sure and they are correct.

Also tried without the Prefix - but it makes no difference:

[3/19/2023, 7:19:17 AM] [homebridge-melcloud-control] MQTT Connect error: Error: Connection refused: Not authorized

**Comment by grzegorz914** [comment]
added in 0.10.1

**Comment by JornDL** [comment]
That was super quick :-)

I just tried it, but it seems, that it uses another ID than the one I put in the config:

Config:
"mqttClientId": "melcloud_2_mosquitto"

Mosquitto log:
1679208806: New connection from 127.0.0.1:47476 on port 1883.
1679208806: Client mqttjs_7b8e0617 disconnected, not authorised.

Homebridge log:
[3/19/2023, 7:53:26 AM] [homebridge-melcloud-control] MQTT Connect error: Error: Connection refused: Not authorized

Mosquitto log - When I connect from my PC with MQTT explorer:
1679206392: New connection from 192.168.1.245:51471 on port 1883.
1679206392: New client connected from 192.168.1.245:51471 as mqtt-explorer-4286441e (p2, c1, k60, u'jorn').

**Comment by JornDL** [comment]
I don't know if it makes any difference - but I'm running in a child bridge

**Comment by JornDL** [comment]
Also my zigbee2mqtt connection from the same RPi4:

1679187168: New connection from 127.0.0.1:33378 on port 1883.
1679187168: New client connected from 127.0.0.1:33378 as RPi4Main_zigbee2mqtt_2_mosquitto (p2, c1, k60, u'jorn').

**Comment by grzegorz914** [comment]
try again. 0.10.2

**Comment by JornDL** [comment]
Just had breakfast - so a little later:

The log in still fails:
[3/19/2023, 9:38:12 AM] [homebridge-melcloud-control] MQTT Connect error: Error: Connection refused: Not authorized

But It now uses the correct Client ID:
Config:
"mqttClientId": "melcloud_2_mosquitto"

Mosquitto log:
1679215092: New connection from 127.0.0.1:49278 on port 1883.
1679215092: Client melcloud_2_mosquitto disconnected, not authorised.

I can't what understand what is wrong - or what I'm doing wrong - mqqt section from config:
                    "enableMqtt": true,
                    "mqttDebug": false,
                    "mqttHost": "127.0.0.1",
                    "mqttClientId": "melcloud_2_mosquitto",
                    "mqttPrefix": "melcloud/kitchen",
                    "mqttAuth": true,
                    "mqttUser": "jorn",
                    "mqttPasswd": "********"
The user/password is correct - also used in the same config for another plugin.

**Comment by grzegorz914** [comment]
May be try not use 127.0.0.1, set full address of mqtt server

**Comment by JornDL** [comment]
Tried that also without any luck

**Comment by grzegorz914** [comment]
Strange, here all working correct, mosquito as broker on Mac. Check your broker authentication setting: https://mosquitto.org/documentation/authentication-methods/

**Comment by grzegorz914** [comment]
If your broker working only inside local network the you can allow unauthenticated access

**Comment by tonyp62** [comment]
Hello @grzegorz914 and everyone. i have an issue with mqtt. 
Mosquitto MQTT is installed under the same machine and it's connected from other mqtt clients (MQTTX,Domoticz, and so on), but not from the plugin. Configuration is been made from Config UI X . No Client ID is written into config (also if i write, same error below) and when plugin starts, report:
1748108643: New connection from 127.0.0.1:48424 on port 1883.
1748108643: New connection from 127.0.0.1:48434 on port 1883.
1748108643: New connection from 127.0.0.1:48442 on port 1883.
1748108643: New connection from 127.0.0.1:48448 on port 1883.
1748108643: New connection from 127.0.0.1:48454 on port 1883.
1748108643: Client <unknown> disconnected, not authorised.
1748108643: Client <unknown> disconnected, not authorised.
1748108643: Client <unknown> disconnected, not authorised.
1748108643: Client <unknown> disconnected, not authorised.
1748108643: Client <unknown> disconnected, not authorised.

How can i solve ?
Thanks All.
