### ISSUE TITLE
Heat Pump show up under Accessories in the Homebridge UI, but not in the Home app

### ISSUE THREAD

**Issue by bjornand1** [grzegorz914/homebridge-melcloud-control#36]
Hi, I just installed this plugin, running as child bridge. The heat pump displays under accessories in the UI, but it just won't show up in the Apple Home app. Any ideas what could be causing this?

**Comment by bjornand1** [comment]
Done now, thanks!

**Comment by bjornand1** [comment]
Hmm, now I have added the child bridge, but the actual heat pump does not get integrated into Home.

**Comment by grzegorz914** [comment]
You not read the wiki carefully, You need to add the accessory itself not the bridge
