### ISSUE TITLE
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block

### ISSUE THREAD

**Issue by Reliktdragons** [grzegorz914/homebridge-melcloud-control#39]
I always get this message:

03/04/2023, 12:01:08] [Homebridge UI] Running Command: npm install --save homebridge-melcloud-control@0.11.8
[03/04/2023, 12:02:48] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<UserRequestError>".
[03/04/2023, 12:03:54] Got SIGTERM, shutting down Homebridge...

Almost always when I want to update the MELCloud plugin. Other plugins can be updated without problems.
Sometimes even without an update.

**Comment by grzegorz914** [comment]
This error have nothing to do with plugin, try completely remove and install from scratch.

**Comment by Reliktdragons** [comment]
Error still comes.
Even after reinstalling Homebridge.
I will try it soon on a second raspberry pi

**Comment by grzegorz914** [comment]
I need full debug log, this info is not from plugin itself. How do you install it, use Config UI X or Comand line?

**Comment by grzegorz914** [comment]
Please provide full info, Homebridge version, Node version, config.json, registered device types on MELCloud.

**Comment by Reliktdragons** [comment]
I have completely reinstalled everything and updated everything to the latest status.

now it works.

**Comment by grzegorz914** [comment]
Nice.
