### ISSUE TITLE
Model Name and Serial Number are not properly displayed in HK

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#4]
In homekit model and serial number are not from the unit, but from the wifi interface. AA info should be coming from property Devices.Device."Units": [
              {
                "SerialNumber": "8XHXXXXX,
                "Model": "SEZ-XXXXXX",
                "UnitType": 1,
                "IsIndoor": true
              }

**Comment by grzegorz914** [comment]
fixed in 0.2.6

**Comment by CyberMrProper** [comment]
Thanks!
