### ISSUE TITLE
Adding accessory to HomeKit

### ISSUE THREAD

**Issue by jsolismar** [grzegorz914/homebridge-melcloud-control#40]
hi @grzegorz914, firstly many thanks for your contribution. I have started this week working with homebridge and your plugins are really useful.
I would like to ask you about adding the air conditioner to HomeKit,  I can see the accessory in homebridge but not in HomeKit.
I attached config and debug details.
Thanks

[Air conditioner debug.pdf](https://github.com/grzegorz914/homebridge-melcloud-control/files/11183740/Air.conditioner.debug.pdf)
[config.pdf](https://github.com/grzegorz914/homebridge-melcloud-control/files/11183741/config.pdf)

**Comment by grzegorz914** [comment]
Are You added it to HomeKit? 
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#adding-to-homekit

**Comment by jsolismar** [comment]
Yes, I did it many times. But I tried again after sending your comment and the AC was in HomeKit. Thanks again for the plugin and your support.
