### ISSUE TITLE
Account MyAccount, login error, Error: unable to verify the first certificate, reconnect in 65s

### ISSUE THREAD

**Issue by ams158** [grzegorz914/homebridge-melcloud-control#46]
Today, suddenly the MELcloud plugin stopped working. When checking my Homebridge logs, I see this message:

`[5/10/2023, 7:28:15 PM] [homebridge-melcloud-control] Account MyAccount, login error, Error: unable to verify the first certificate, reconnect in 65s.`

The service works through MELcloud app, any idea why suddenly started to fail? I've been using it for months.

Thanks, BR
Abel

**Comment by Reliktdragons** [comment]
with me also the same error in the log

**Comment by Lechucico** [comment]
Same error here

**Comment by easyproger** [comment]
Fix: 
npm install --save node_extra_ca_certs_mozilla_bundle

and in melcloud.js add

in header:
const fs = require('fs');
const https = require('https');

in constructor: 
https.globalAgent.options.ca = fs.readFileSync('node_modules/node_extra_ca_certs_mozilla_bundle/ca_bundle/ca_intermediate_root_bundle.pem');

**Comment by abuapfbua** [comment]
The website https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin is no longer available.

**Comment by abuapfbua** [comment]
> s through MELcloud
The website https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin is no longer available.

**Comment by mlamieri** [comment]
Same issue here

**Comment by bddq** [comment]
Same issue here.

**Comment by MorreMor** [comment]
Same issue here, please update plugin

**Comment by abuapfbua** [comment]
thanks @grzegorz914, it works perfectly.
