### ISSUE TITLE
cannot read proprieties of null

### ISSUE THREAD

**Issue by spazuino** [grzegorz914/homebridge-melcloud-control#47]
few weeks after installing and setting up the plugin out of nowhere got the following error:
`[homebridge-melcloud-control] Account Alessio, login error, TypeError: Cannot read properties of null (reading 'ContextKey'), reconnect in 65s.`
and have no clue about it, tried reinserting the account info and reinstalling but nothing.

**Comment by grzegorz914** [comment]
Still the issue, i don't see any problem on my side. May be was temporary server problem.?

**Comment by spazuino** [comment]
I removed the plug-in, restarted the raspi and configured it like the first time and worked Kony know how
