### ISSUE TITLE
Extra Buttons don't work

### ISSUE THREAD

**Issue by Loggss** [grzegorz914/homebridge-melcloud-control#48]
Extra buttons don't work in the last version. I have two air conditionners (linked to Melcloud), and even if the AC work well in homekit, extra buttons don't appears.

**Comment by grzegorz914** [comment]
What button, any log, Config, more info.

**Comment by Loggss** [comment]
I have two splits well recognised and updated in HomeKit thanks for the plug-in (used in hoobs)

I tested 4 different buttons : on/off, purify, fan auto and dry, but none appears in HomeKit. Do I have a special manipulation to do to see or add buttons ? (I don’t use Mqtt)

I already test to suppress all the AC and the bridge linked to HomeKit, and clear the cache

**Comment by grzegorz914** [comment]
Already tested and and button are here after enable it, can you post your Config.json? any info in log after restart plugin?

![IMG_0835](https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/bf6fc82b-00bc-479e-8792-dda18980e1f8)

**Comment by Loggss** [comment]
Thanks for your reply.

Here you find my config :

`{
    "platform": "melcloudcontrol",
    "accounts": [
        {
            "name": "myname",
            "user": "xxx",
            "passwd": "xxx",
            "language": "7",
            "displayMode": 0,
            "enableMqtt": true,
            "enableDebugMode": true,
            "buttons": [
                {
                    "name": "Purifier",
                    "mode": "9",
                    "displayType": 1
                },
                {
                    "name": "on/off",
                    "mode": "0",
                    "displayType": 0
                },
                {
                    "name": "fan",
                    "mode": "25",
                    "displayType": 0
                }
            ],
            "disableLogDeviceInfo": true
        }
    ]
}`

and here you find the .log :
`21/05/2023 08:18:24Melcloud Control BridgemelcloudcontrolAccount XXX, debug: Found: 2 devices.
21/05/2023 08:18:27Melcloud Control BridgemelcloudcontrolAir Conditioner, Mitsubishi Véranda, debug: Info: {
  "DeviceID": XXX,
  "DeviceName": "Mitsubishi Véranda",
  "BuildingID": XX,
  "BuildingName": null,
  "FloorID": null,
  "FloorName": null,
  "AreaID": null,
  "AreaName": null,
  "ImageID": XX,
  "InstallationDate": "2024-02-29T00:00:00",
  "LastServiceDate": "2024-02-29T00:00:00",
  "Presets": [],
  "OwnerID": XX,
  "OwnerName": null,
  "OwnerEmail": null,
  "AccessLevel": 4,
  "DirectAccess": false,
  "EndDate": "2500-01-01T00:00:00",
  "Zone1Name": null,
  "Zone2Name": null,
  "MinTemperature": 0,
  "MaxTemperature": 40,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "HideRoomTemperature": false,
  "HideSupplyTemperature": false,
  "HideOutdoorTemperature": false,
  "BuildingCountry": null,
  "OwnerCountry": null,
  "AdaptorType": 3,
  "LinkedDevice": "xxx",
  "Type": 0,
  "MacAddress": "xx",
  "SerialNumber": "xx",
  "Device": {
    "PCycleActual": 0,
    "ErrorMessages": "",
    "DeviceType": 0,
    "CanCool": true,
    "CanHeat": true,
    "CanDry": true,
    "HasAutomaticFanSpeed": true,
    "AirDirectionFunction": true,
    "SwingFunction": true,
    "NumberOfFanSpeeds": 5,
    "UseTemperatureA": true,
    "TemperatureIncrementOverride": 0,
    "TemperatureIncrement": 0.5,
    "MinTempCoolDry": 16,
    "MaxTempCoolDry": 31,
    "MinTempHeat": 10,
    "MaxTempHeat": 31,
    "MinTempAutomatic": 16,
    "MaxTempAutomatic": 31,
    "LegacyDevice": false,
    "UnitSupportsStandbyMode": true,
    "IsSplitSystem": true,
    "ModelIsAirCurtain": false,
    "ModelSupportsFanSpeed": true,
    "ModelSupportsAuto": true,
    "ModelSupportsHeat": true,
    "ModelSupportsDry": true,
    "ModelSupportsVaneVertical": true,
    "ModelSupportsVaneHorizontal": true,
    "ModelSupportsWideVane": true,
    "ModelDisableEnergyReport": false,
    "ModelSupportsStandbyMode": true,
    "ModelSupportsEnergyReporting": true,
    "ProhibitSetTemperature": false,
    "ProhibitOperationMode": false,
    "ProhibitPower": false,
    "Power": true,
    "RoomTemperature": 20,
    "SetTemperature": 22,
    "ActualFanSpeed": 1,
    "FanSpeed": 0,
    "AutomaticFanSpeed": true,
    "VaneVerticalDirection": 0,
    "VaneVerticalSwing": false,
    "VaneHorizontalDirection": 0,
    "VaneHorizontalSwing": false,
    "OperationMode": 1,
    "EffectiveFlags": 0,
    "LastEffectiveFlags": 0,
    "InStandbyMode": false,
    "DemandPercentage": 100,
    "ConfiguredDemandPercentage": null,
    "HasDemandSideControl": false,
    "DefaultCoolingSetTemperature": 21,
    "DefaultHeatingSetTemperature": 23,
    "RoomTemperatureLabel": 0,
    "HeatingEnergyConsumedRate1": 0,
    "HeatingEnergyConsumedRate2": 0,
    "CoolingEnergyConsumedRate1": 0,
    "CoolingEnergyConsumedRate2": 0,
    "AutoEnergyConsumedRate1": 0,
    "AutoEnergyConsumedRate2": 0,
    "DryEnergyConsumedRate1": 0,
    "DryEnergyConsumedRate2": 0,
    "FanEnergyConsumedRate1": 0,
    "FanEnergyConsumedRate2": 0,
    "OtherEnergyConsumedRate1": 0,
    "OtherEnergyConsumedRate2": 0,
    "HasEnergyConsumedMeter": true,
    "CurrentEnergyConsumed": 100,
    "CurrentEnergyMode": 1,
    "CoolingDisabled": false,
    "EnergyCorrectionModel": 918,
    "EnergyCorrectionActive": false,
    "MinPcycle": 1,
    "MaxPcycle": 1,
    "EffectivePCycle": 1,
    "MaxOutdoorUnits": 255,
    "MaxIndoorUnits": 255,
    "MaxTemperatureControlUnits": 0,
    "ModelCode": "0130",
    "DeviceID": xx,
    "MacAddress": "xx",
    "SerialNumber": "xx",
    "TimeZoneID": 121,
    "DiagnosticMode": 0,
    "DiagnosticEndDate": null,
    "ExpectedCommand": 1,
    "Owner": 738602,
    "DetectedCountry": null,
    "AdaptorType": 3,
    "FirmwareDeployment": null,
    "FirmwareUpdateAborted": false,
    "LinkedDevice": "xx",
    "WifiSignalStrength": -43,
    "WifiAdapterStatus": "NORMAL",
    "Position": "Unknown",
    "PCycle": 10,
    "PCycleConfigured": null,
    "RecordNumMax": 0,
    "LastTimeStamp": "2023-05-21T08:17:00",
    "ErrorCode": 8000,
    "HasError": false,
    "LastReset": "2023-05-19T12:56:10.83",
    "FlashWrites": 2,
    "Scene": null,
    "SSLExpirationDate": "2037-12-31T00:00:00",
    "SPTimeout": 1,
    "Passcode": null,
    "ServerCommunicationDisabled": false,
    "ConsecutiveUploadErrors": 0,
    "DoNotRespondAfter": null,
    "OwnerRoleAccessLevel": 1,
    "OwnerCountry": 78,
    "HideEnergyReport": false,
    "ExceptionHash": null,
    "ExceptionDate": null,
    "ExceptionCount": null,
    "Rate1StartTime": null,
    "Rate2StartTime": null,
    "ProtocolVersion": 0,
    "UnitVersion": 0,
    "FirmwareAppVersion": 37000,
    "FirmwareWebVersion": 0,
    "FirmwareWlanVersion": 0,
    "MqttFlags": 9,
    "HasErrorMessages": false,
    "HasZone2": false,
    "Offline": false,
    "SupportsHourlyEnergyReport": true,
    "Units": [
      {
        "ID": 1,
        "Device": 0,
        "SerialNumber": "xx",
        "ModelNumber": 769,
        "Model": "MXZ-2F53VF(2)HZ",
        "UnitType": 0,
        "IsIndoor": false
      },
      {
        "ID": 2,
        "Device": 0,
        "SerialNumber": "xx",
        "ModelNumber": 918,
        "Model": "MSZ-LN35VG2(W/V/R/B)",
        "UnitType": 1,
        "IsIndoor": true
      }
    ]
  },
  "DiagnosticMode": 0,
  "DiagnosticEndDate": null,
  "Location": xx,
  "DetectedCountry": null,
  "Registrations": 9,
  "LocalIPAddress": null,
  "TimeZone": 121,
  "RegistReason": "CONFIG",
  "ExpectedCommand": 1,
  "RegistRetry": 0,
  "DateCreated": "2023-05-19T12:36:55.988Z",
  "FirmwareDeployment": null,
  "FirmwareUpdateAborted": false,
  "Permissions": {
    "CanSetOperationMode": true,
    "CanSetFanSpeed": true,
    "CanSetVaneDirection": true,
    "CanSetPower": true,
    "CanSetTemperatureIncrementOverride": true,
    "CanDisableLocalController": true,
    "CanSetDemandSideControl": false
  }
}
21/05/2023 08:18:27Melcloud Control BridgemelcloudcontrolAir Conditioner, Mitsubishi TV, debug: Info: {
  "DeviceID": xx,
  "DeviceName": "Mitsubishi TV",
  "BuildingID": xx,
  "BuildingName": null,
  "FloorID": null,
  "FloorName": null,
  "AreaID": null,
  "AreaName": null,
  "ImageID": xx,
  "InstallationDate": "2024-04-30T00:00:00",
  "LastServiceDate": "2024-04-30T00:00:00",
  "Presets": [],
  "OwnerID": xx,
  "OwnerName": null,
  "OwnerEmail": null,
  "AccessLevel": 4,
  "DirectAccess": false,
  "EndDate": "2500-01-01T00:00:00",
  "Zone1Name": null,
  "Zone2Name": null,
  "MinTemperature": 0,
  "MaxTemperature": 40,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "HideRoomTemperature": false,
  "HideSupplyTemperature": false,
  "HideOutdoorTemperature": false,
  "BuildingCountry": null,
  "OwnerCountry": null,
  "AdaptorType": 3,
  "LinkedDevice": "xx",
  "Type": 0,
  "MacAddress": "xx",
  "SerialNumber": "xx",
  "Device": {
    "PCycleActual": 0,
    "ErrorMessages": "",
    "DeviceType": 0,
    "CanCool": true,
    "CanHeat": true,
    "CanDry": true,
    "HasAutomaticFanSpeed": true,
    "AirDirectionFunction": true,
    "SwingFunction": true,
    "NumberOfFanSpeeds": 5,
    "UseTemperatureA": true,
    "TemperatureIncrementOverride": 0,
    "TemperatureIncrement": 0.5,
    "MinTempCoolDry": 16,
    "MaxTempCoolDry": 31,
    "MinTempHeat": 10,
    "MaxTempHeat": 31,
    "MinTempAutomatic": 16,
    "MaxTempAutomatic": 31,
    "LegacyDevice": false,
    "UnitSupportsStandbyMode": true,
    "IsSplitSystem": true,
    "ModelIsAirCurtain": false,
    "ModelSupportsFanSpeed": true,
    "ModelSupportsAuto": true,
    "ModelSupportsHeat": true,
    "ModelSupportsDry": true,
    "ModelSupportsVaneVertical": true,
    "ModelSupportsVaneHorizontal": true,
    "ModelSupportsWideVane": true,
    "ModelDisableEnergyReport": false,
    "ModelSupportsStandbyMode": true,
    "ModelSupportsEnergyReporting": true,
    "ProhibitSetTemperature": false,
    "ProhibitOperationMode": false,
    "ProhibitPower": false,
    "Power": true,
    "RoomTemperature": 19,
    "SetTemperature": 22,
    "ActualFanSpeed": 1,
    "FanSpeed": 0,
    "AutomaticFanSpeed": true,
    "VaneVerticalDirection": 0,
    "VaneVerticalSwing": false,
    "VaneHorizontalDirection": 0,
    "VaneHorizontalSwing": false,
    "OperationMode": 1,
    "EffectiveFlags": 0,
    "LastEffectiveFlags": 0,
    "InStandbyMode": false,
    "DemandPercentage": 100,
    "ConfiguredDemandPercentage": null,
    "HasDemandSideControl": false,
    "DefaultCoolingSetTemperature": 21,
    "DefaultHeatingSetTemperature": 23,
    "RoomTemperatureLabel": 0,
    "HeatingEnergyConsumedRate1": 0,
    "HeatingEnergyConsumedRate2": 0,
    "CoolingEnergyConsumedRate1": 0,
    "CoolingEnergyConsumedRate2": 0,
    "AutoEnergyConsumedRate1": 0,
    "AutoEnergyConsumedRate2": 0,
    "DryEnergyConsumedRate1": 0,
    "DryEnergyConsumedRate2": 0,
    "FanEnergyConsumedRate1": 0,
    "FanEnergyConsumedRate2": 0,
    "OtherEnergyConsumedRate1": 0,
    "OtherEnergyConsumedRate2": 0,
    "HasEnergyConsumedMeter": true,
    "CurrentEnergyConsumed": 10100,
    "CurrentEnergyMode": 1,
    "CoolingDisabled": false,
    "EnergyCorrectionModel": 918,
    "EnergyCorrectionActive": false,
    "MinPcycle": 1,
    "MaxPcycle": 1,
    "EffectivePCycle": 1,
    "MaxOutdoorUnits": 255,
    "MaxIndoorUnits": 255,
    "MaxTemperatureControlUnits": 0,
    "ModelCode": "0130",
    "DeviceID": xx,
    "MacAddress": "xx",
    "SerialNumber": "xx",
    "TimeZoneID": 121,
    "DiagnosticMode": 0,
    "DiagnosticEndDate": null,
    "ExpectedCommand": 1,
    "Owner": 738602,
    "DetectedCountry": null,
    "AdaptorType": 3,
    "FirmwareDeployment": null,
    "FirmwareUpdateAborted": false,
    "LinkedDevice": "xx",
    "WifiSignalStrength": -38,
    "WifiAdapterStatus": "NORMAL",
    "Position": "Unknown",
    "PCycle": 10,
    "PCycleConfigured": null,
    "RecordNumMax": 0,
    "LastTimeStamp": "2023-05-21T08:16:00",
    "ErrorCode": 8000,
    "HasError": false,
    "LastReset": "2023-05-19T12:55:55.473",
    "FlashWrites": 2,
    "Scene": null,
    "SSLExpirationDate": "2037-12-31T00:00:00",
    "SPTimeout": 1,
    "Passcode": null,
    "ServerCommunicationDisabled": false,
    "ConsecutiveUploadErrors": 0,
    "DoNotRespondAfter": null,
    "OwnerRoleAccessLevel": 1,
    "OwnerCountry": 78,
    "HideEnergyReport": false,
    "ExceptionHash": null,
    "ExceptionDate": null,
    "ExceptionCount": null,
    "Rate1StartTime": null,
    "Rate2StartTime": null,
    "ProtocolVersion": 0,
    "UnitVersion": 0,
    "FirmwareAppVersion": 37000,
    "FirmwareWebVersion": 0,
    "FirmwareWlanVersion": 0,
    "MqttFlags": 9,
    "HasErrorMessages": false,
    "HasZone2": false,
    "Offline": false,
    "SupportsHourlyEnergyReport": true,
    "Units": [
      {
        "ID": 1,
        "Device": 0,
        "SerialNumber": "xx",
        "ModelNumber": 769,
        "Model": "MXZ-2F53VF(2)HZ",
        "UnitType": 0,
        "IsIndoor": false
      },
      {
        "ID": 2,
        "Device": 0,
        "SerialNumber": "xx",
        "ModelNumber": 917,
        "Model": "MSZ-LN25VG2(W/V/R/B)",
        "UnitType": 1,
        "IsIndoor": true
      },
      {
        "ID": 3,
        "Device": 0,
        "SerialNumber": "xx",
        "ModelNumber": 918,
        "Model": "MSZ-LN35VG2(W/V/R/B)",
        "UnitType": 1,
        "IsIndoor": true
      }
    ]
  },
  "DiagnosticMode": 0,
  "DiagnosticEndDate": null,
  "Location": xx,
  "DetectedCountry": null,
  "Registrations": 9,
  "LocalIPAddress": null,
  "TimeZone": 121,
  "RegistReason": "CONFIG",
  "ExpectedCommand": 1,
  "RegistRetry": 0,
  "DateCreated": "2023-05-19T12:32:25.474Z",
  "FirmwareDeployment": null,
  "FirmwareUpdateAborted": false,
  "Permissions": {
    "CanSetOperationMode": true,
    "CanSetFanSpeed": true,
    "CanSetVaneDirection": true,
    "CanSetPower": true,
    "CanSetTemperatureIncrementOverride": true,
    "CanDisableLocalController": true,
    "CanSetDemandSideControl": false
  }
}
21/05/2023 08:18:28Melcloud Control BridgemelcloudcontrolAir Conditioner, Mitsubishi Véranda, debug: State: {
  "EffectiveFlags": 0,
  "LocalIPAddress": null,
  "RoomTemperature": 20,
  "SetTemperature": 22,
  "SetFanSpeed": 0,
  "OperationMode": 1,
  "VaneHorizontal": 0,
  "VaneVertical": 0,
  "Name": null,
  "NumberOfFanSpeeds": 5,
  "WeatherObservations": [
    {
      "Date": "2023-05-21T09:00:00",
      "Sunrise": "2023-05-21T06:28:00",
      "Sunset": "2023-05-21T21:31:00",
      "Condition": 116,
      "ID": xx,
      "Humidity": 80,
      "Temperature": 16,
      "Icon": "wsymbol_0002_sunny_intervals",
      "ConditionName": "Partiellement nuageux",
      "Day": 0,
      "WeatherType": 0
    },
    {
      "Date": "2023-05-21T15:00:00",
      "Sunrise": "2023-05-21T06:28:00",
      "Sunset": "2023-05-21T21:31:00",
      "Condition": 353,
      "ID": xx,
      "Humidity": 52,
      "Temperature": 22,
      "Icon": "wsymbol_0009_light_rain_showers",
      "ConditionName": "Légère averse",
      "Day": 0,
      "WeatherType": 1
    },
    {
      "Date": "2023-05-22T03:00:00",
      "Sunrise": "2023-05-22T06:27:00",
      "Sunset": "2023-05-22T21:32:00",
      "Condition": 116,
      "ID": xx,
      "Humidity": 93,
      "Temperature": 14,
      "Icon": "wsymbol_0008_clear_sky_night",
      "ConditionName": "Partiellement nuageux",
      "Day": 0,
      "WeatherType": 2
    },
    {
      "Date": "2023-05-22T15:00:00",
      "Sunrise": "2023-05-22T06:27:00",
      "Sunset": "2023-05-22T21:32:00",
      "Condition": 386,
      "ID": xx,
      "Humidity": 61,
      "Temperature": 23,
      "Icon": "wsymbol_0016_thundery_showers",
      "ConditionName": "Légère pluie dans une zone orageuse par endroits",
      "Day": 1,
      "WeatherType": 1
    }
  ],
  "ErrorMessage": null,
  "ErrorCode": 8000,
  "DefaultHeatingSetTemperature": 23,
  "DefaultCoolingSetTemperature": 21,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "RoomTemperatureLabel": 0,
  "InStandbyMode": false,
  "TemperatureIncrementOverride": 0,
  "ProhibitSetTemperature": false,
  "ProhibitOperationMode": false,
  "ProhibitPower": false,
  "DemandPercentage": 100,
  "DeviceID": xx,
  "DeviceType": 0,
  "LastCommunication": "2023-05-21T06:18:27.071",
  "NextCommunication": "2023-05-21T06:19:27.071",
  "Power": true,
  "HasPendingCommand": false,
  "Offline": false,
  "Scene": null,
  "SceneOwner": null
}
21/05/2023 08:18:28Melcloud Control BridgemelcloudcontrolAir Conditioner, Mitsubishi TV, debug: State: {
  "EffectiveFlags": 0,
  "LocalIPAddress": null,
  "RoomTemperature": 19,
  "SetTemperature": 22,
  "SetFanSpeed": 0,
  "OperationMode": 1,
  "VaneHorizontal": 0,
  "VaneVertical": 0,
  "Name": null,
  "NumberOfFanSpeeds": 5,
  "WeatherObservations": [
    {
      "Date": "2023-05-21T09:00:00",
      "Sunrise": "2023-05-21T06:28:00",
      "Sunset": "2023-05-21T21:31:00",
      "Condition": 116,
      "ID": xx,
      "Humidity": 80,
      "Temperature": 16,
      "Icon": "wsymbol_0002_sunny_intervals",
      "ConditionName": "Partiellement nuageux",
      "Day": 0,
      "WeatherType": 0
    },
    {
      "Date": "2023-05-21T15:00:00",
      "Sunrise": "2023-05-21T06:28:00",
      "Sunset": "2023-05-21T21:31:00",
      "Condition": 353,
      "ID": xx,
      "Humidity": 52,
      "Temperature": 22,
      "Icon": "wsymbol_0009_light_rain_showers",
      "ConditionName": "Légère averse",
      "Day": 0,
      "WeatherType": 1
    },
    {
      "Date": "2023-05-22T03:00:00",
      "Sunrise": "2023-05-22T06:27:00",
      "Sunset": "2023-05-22T21:32:00",
      "Condition": 116,
      "ID": xx,
      "Humidity": 93,
      "Temperature": 14,
      "Icon": "wsymbol_0008_clear_sky_night",
      "ConditionName": "Partiellement nuageux",
      "Day": 0,
      "WeatherType": 2
    },
    {
      "Date": "2023-05-22T15:00:00",
      "Sunrise": "2023-05-22T06:27:00",
      "Sunset": "2023-05-22T21:32:00",
      "Condition": 386,
      "ID": xx,
      "Humidity": 61,
      "Temperature": 23,
      "Icon": "wsymbol_0016_thundery_showers",
      "ConditionName": "Légère pluie dans une zone orageuse par endroits",
      "Day": 1,
      "WeatherType": 1
    }
  ],
  "ErrorMessage": null,
  "ErrorCode": 8000,
  "DefaultHeatingSetTemperature": 23,
  "DefaultCoolingSetTemperature": 21,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "RoomTemperatureLabel": 0,
  "InStandbyMode": false,
  "TemperatureIncrementOverride": 0,
  "ProhibitSetTemperature": false,
  "ProhibitOperationMode": false,
  "ProhibitPower": false,
  "DemandPercentage": 100,
  "DeviceID": xx,
  "DeviceType": 0,
  "LastCommunication": "2023-05-21T06:18:26.909",
  "NextCommunication": "2023-05-21T06:19:26.909",
  "Power": true,
  "HasPendingCommand": false,
  "Offline": false,
  "Scene": null,
  "SceneOwner": null
}`

**Comment by grzegorz914** [comment]
You have all correct, the Button need to be visible. If You can Please post whole debug log direct after restart plugin.

**Comment by Loggss** [comment]
I just uninstall, and re install previous version
I check logs and see this:

`ERRORError: write EPIPE at ChildProcess.target._send (node:internal/child_process:874:20) at ChildProcess.target.send (node:internal/child_process:747:19) at /usr/src/hub/services/socket.ts:66:33 at new Promise (<anonymous>) at Socket.fetch (/usr/src/hub/services/socket.ts:50:16) at /usr/src/hub/services/ipc.ts:39:41 at new Promise (<anonymous>) at HubIPC.fetch (/usr/src/hub/services/ipc.ts:35:16) at /usr/src/hub/services/monitor.ts:35:28 at new Promise (<anonymous>) at Monitor (/usr/src/hub/services/monitor.ts:34:24) at Timeout._a [as _onTimeout] (/usr/src/hub/services/monitor.ts:88:44) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) `

What I am supposed to do ? According to you ? Currently the bridge is not set as a child one but as an additional one. Does it can impact this functionalities ?

**Comment by grzegorz914** [comment]
The error is not from plugin, as I described before I need full debug log, enable it in plugin advanced section, restart plugin only and get the whole log.

**Comment by Loggss** [comment]
I tried to. I get this:

`21/05/2023 16:18:56Melcloud Control BridgeLoaded plugin 'homebridge-melcloud-control'
21/05/2023 16:18:56Melcloud Control BridgeRegistering platform 'homebridge-melcloud-control.melcloudcontrol'
21/05/2023 16:18:56Melcloud Control BridgeLoading 1 platforms...
21/05/2023 16:18:56Melcloud Control BridgemelcloudcontrolAccount xxx, did finish launching.
21/05/2023 16:18:57Melcloud Control BridgeBridge is running on port 51836.
21/05/2023 16:18:57Securitysystem BridgeBridge is running on port 51826.
21/05/2023 16:18:57Securitysystem BridgeSystemeSaved state (Found)
21/05/2023 16:18:57Melcloud Control BridgemelcloudcontrolAccount xxx, debug: MELCloud Info: {
  "ErrorId": 5,
  "ErrorMessage": null,
  "LoginStatus": 0,
  "UserId": 0,
  "RandomKey": null,
  "AppVersionAnnouncement": null,
  "LoginData": {
    "ContextKey": "xxx",
    "Client": xx,
    "Terms": xx,
    "AL": 1,
    "ML": 0,
    "CMI": true,
    "IsStaff": false,
    "CUTF": false,
    "CAA": false,
    "ReceiveCountryNotifications": false,
    "ReceiveAllNotifications": false,
    "CACA": false,
    "CAGA": false,
    "MaximumDevices": 10,
    "ShowDiagnostics": false,
    "Language": 7,
    "Country": 78,
    "RealClient": 0,
    "Name": "xx",
    "UseFahrenheit": false,
    "Duration": 525600,
    "Expiry": "2024-05-20T14:18:57.18",
    "CMSC": false,
    "PartnerApplicationVersion": null,
    "EmailSettingsReminderShown": true,
    "EmailUnitErrors": 2,
    "EmailCommsErrors": 2,
    "ChartSeriesHidden": 0,
    "DeletePending": false,
    "IsImpersonated": false,
    "LanguageCode": "fr",
    "CountryName": "France",
    "CurrencySymbol": "€",
    "SupportEmailAddress": "tech.clim@fra.mee.com",
    "DateSeperator": "/",
    "TimeSeperator": ":",
    "AtwLogoFile": "ecodan_logo.png",
    "DECCReport": false,
    "CSVReport1min": false,
    "HidePresetPanel": false,
    "EmailSettingsReminderRequired": false,
    "TermsText": null,
    "MapView": false,
    "MapZoom": 21,
    "MapLongitude": xx,
    "MapLatitude": xx
  },
  "ListPendingInvite": [],
  "ListOwnershipChangeRequest": [],
  "ListPendingAnnouncement": [],
  "LoginMinutes": 0,
  "LoginAttempts": 0
}`

Is it the right log ?

**Comment by grzegorz914** [comment]
Download log from here and post here:
![IMG_0837](https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/8b142dff-72a8-4b33-96dc-1260ac32f238)

**Comment by Loggss** [comment]
I use Hoobs (not exactly Homebridge UI), but the log file seems to be similar. Please find it attached
[log file.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/11524894/log.file.txt)

**Comment by grzegorz914** [comment]
I found something strange in log:

```
21/05/2023 15:23:32 Securitysystem Bridge Melcloud Control Bridge starting
21/05/2023 15:24:00 Melcloud Control Bridge Loaded plugin 'homebridge-melcloud-control'
21/05/2023 15:24:00 Melcloud Control Bridge Loading 1 platforms...
21/05/2023 15:24:00 Melcloud Control Bridge melcloudcontrol [ WARNING ] No configuration found for homebridge-melcloud-control
```

check your config.json, may be remove manually whole plugin config and configure it again, also run as child bridge .

**Comment by Loggss** [comment]
It could make sense... Can I found a config.json file in the terminal through SSH connection ? I already suppress and re-create the config thanks to the UI in hoobs

**Comment by grzegorz914** [comment]
/var/lib/homebridge on rpi

**Comment by grzegorz914** [comment]
in HOOBS can be in different path

**Comment by Loggss** [comment]
Thanks. I just checked, path is similar in hoobs: /var/lib/hoobs/"bridgename"/config.json.
Unfortunately, the config.json is good (the same than in the Hoobs UI). What do you think about?

**Comment by Loggss** [comment]
okay. eventually do you have any advice to reset/update node ?

**Comment by grzegorz914** [comment]
I close this because the buttons working correct
