### ISSUE TITLE
Stop Working on HOOBS

### ISSUE THREAD

**Issue by simposiummm** [grzegorz914/homebridge-melcloud-control#50]
Hi

For unexpected reason the device that works previously on HOOBS stop working.

I just follow normal and basic test.

Restart the bridge
Unistall plugin 
Install Again

Nothing this make it works again. On logs i can see that plugin can retrieve the information successfully from MeCloud account
 
6/19/2023, 4:55:00 melcloudcontrol---- Air Conditioner: Clima Casa ----
6/19/2023, 4:55:00 melcloudcontrolAccount: Casa
6/19/2023, 4:55:00 melcloudcontrolSerial: 2101069086
6/19/2023, 4:55:00 melcloudcontrolFirmware: 19000
6/19/2023, 4:55:00 melcloudcontrolManufacturer: Mitsubishi
6/19/2023, 4:55:00 melcloudcontrol----------------------------------

If i enable the debug also i can see more parameters from the MeCloud

With this situation my the device is not added automatically on the default room via the HOOBS bridge and there is no reason to understand why stop working after more than 1 year and a half :(

Appreciated your answer and thanks for the fantastic work on this addom

**Comment by grzegorz914** [comment]
What you mean stop working, is not respond in homekit app, not react on command ?

**Comment by simposiummm** [comment]
originally not respond on homekit app, after delete this device is not
longer possible to join the homekit app but is working aparently on Hoobs

Any idea welcome!

**Comment by grzegorz914** [comment]
Try this https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by simposiummm** [comment]
Thanks for the quick answer
On HOOBS just i used as you mentioned the Purge Option

On the terminal:
sudo hbs bridge purge

Appreciated your support on this :)
