### ISSUE TITLE
Lock physical controls

### ISSUE THREAD

**Issue by ivnikol18** [grzegorz914/homebridge-melcloud-control#51]
Firstly, many thanks for the great plugin. I was so annoyed by the need to use MelCloud app.

I believe I am facing a bug with Lock physical controls setting. Here is what's happening:
- If I use separately exposed buttons for Power Lock, Mode Lock or Temp Lock it works as expected. Settings are synchronised with MelCloud and unit successfully. And Remote control follows the settings.
- However if I use HomeKit native Locked/Unlocked toggle (without exposing buttons from the plugin) OR use the button to Lock ALL controls, then at first glance it works well. Unit stops responding on Remote Control (as expected), settings are set to disabled in the MelCloud respectively. But I can't enable it back using HomeKit (regardless of what button I try). From the HomeKit view and from MelCloud view controls seem to be enabled, but remote still can't be used. 
I already started to panic, but luckily disabling and re-enabling controls via MelCloud app fixed it. 
I am able to reproduce this with different remotes and indoor units. 

I am not sure whether / how this could be troubleshoot though as MelCloud settings seem to work according to command from the plugin. 

Is it something you could investigate?

**Comment by grzegorz914** [comment]
Will check it.

**Comment by grzegorz914** [comment]
Can you check this again with latest version, on my side all is working correct.

**Comment by ivnikol18** [comment]
I did update and checked. Unfortunately, behaviour of my units didn't change. 
Do you need any debugging infromation?

**Comment by grzegorz914** [comment]
Yes, enable debug mode in  plugin config advanced section and get the whole log after restart and also try to change physical lock control using home app.

**Comment by grzegorz914** [comment]
Please try 0.12.6-beta.0, probably im found the bug

**Comment by ivnikol18** [comment]
It seems my knowledge is insufficient. is there a way to run both latest and beta plugin? or I should uninstall 0.12.5 first?

**Comment by grzegorz914** [comment]
And, still the issue exist?

**Comment by ivnikol18** [comment]
Sorry for a delay here. Yes the issue still exist. I have five indoor units, so debug log is getting pretty big. I also would like to clean it from any personal data. I will take few more days to prepare it for you.

**Comment by grzegorz914** [comment]
I have tested this on my 6 devices MSZ-LN all functions working correct, using native app the lick/unlock working correct and the MELCloud app reflect correct states. Button and native lock/unlock in home app realize same function, so both working in same way.

**Comment by grzegorz914** [comment]
Please  get the debug log during lock/unlock.

**Comment by grzegorz914** [comment]
Ok, I can reproduce this on my side, will inwestowane into this but is very strange that the MELCloud app reflect correct state however the remote still locked.
