### ISSUE TITLE
No Fan Mode for AC unit

### ISSUE THREAD

**Issue by cars11** [grzegorz914/homebridge-melcloud-control#52]
I’ve added my AC unit and it works well, I can control the fan speed under accessory settings homekit, but there is no operation mode “Fan”, only auto, heat and cool.

Any idea why?

Thank you very much

**Comment by grzegorz914** [comment]
Thermostat or Heather/Cooler doesn’t support Fan Mode. You can add extra button for fan mode or replace one of mode function. Please refer to readme to set this possibility.
