### ISSUE TITLE
Added bridge to homekit, however, can't find devices

### ISSUE THREAD

**Issue by adarodge** [grzegorz914/homebridge-melcloud-control#53]
I've followed the directions and understood the bridge will scan/find all my A/C units. This isn't working for me.

Please tell me how to add the physical units to the bridge. I used your sample file and only changed my user/password.

Thank you in advance

**Comment by grzegorz914** [comment]
First of all what a AC device you use? 
Next go to plugin config advanced section and enable debug mode, save and restart the plugin. Next post the whole log.

**Comment by grzegorz914** [comment]
Note, You need to add every AC device to the HomeKit.app
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#adding-to-homekit
