### ISSUE TITLE
Temperature Lookup for automatisation ?

### ISSUE THREAD

**Issue by PedroDeLaFrance** [grzegorz914/homebridge-melcloud-control#54]
Hi !
Is it possible to have a temperature lookup in Home App for make automatisation ?
Best regard's and thank's a lot for your work !

**Comment by grzegorz914** [comment]
If you set Control Mode to Thermostat then is possible create automations based on Themperature in Home app.

**Comment by PedroDeLaFrance** [comment]
Great ! It's work, Thank's.

**Comment by grzegorz914** [comment]
I have pushed 0.12.0 wit integrated temperature sensor for Heater/Cooler control mode, just enable extra sensor in plugin config and have fun.
