### ISSUE TITLE
Accessory display

### ISSUE THREAD

**Issue by feedericob** [grzegorz914/homebridge-melcloud-control#56]
HI,
I configured all the plugin but I can't see the accessories on homekit. For now I see them in homebridge in the accessories tab, I can turn them off and change modes but they don't appear on the various Apple devices.

The car is an air conditioner that makes hot, cold, fan, dry, auto. 2 fun speed.

**Comment by grzegorz914** [comment]
Are you added it to the home app?
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#adding-to-homekit

**Comment by feedericob** [comment]
Many thanks, solved
