### ISSUE TITLE
[melcloudcontrol] Name, user, password or language in config missing.

### ISSUE THREAD

**Issue by jaumebosch** [grzegorz914/homebridge-melcloud-control#57]
Hi, debug is giving this message
[melcloudcontrol] Name, user, password or language in config missing.
tested user and pass through postman and works perfectly.

any idea?

**Comment by grzegorz914** [comment]
Post your config.json please

**Comment by jaumebosch** [comment]
Already checked
user and pass obfuscated for security, also checked and works on melcloud page

`{
            "platform": "melcloudcontrol",
            "accounts": [
                {
                    "name": "MelCloud",
                    "user": "xxxx@xxxxxx.com",
                    "passwd": "xxxxxxx",
                    "language": 0,
                    "ataDisplayMode": 0,
                    "ataTemperatureSensor": true,
                    "ataDisableAutoMode": false,
                    "ataDisableHeatMode": false,
                    "ataAutoHeatMode": 0,
                    "ataPresets": false,
                    "ataButtons": [
                        {
                            "name": "ON/OFF",
                            "mode": 0,
                            "displayType": 0
                        }
                    ],
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableDebugMode": false,
                    "mqttDebug": false,
                    "enableRestFul": false,
                    "restFulDebug": false,
                    "enableMqtt": false
                }
            ]
        }`

**Comment by grzegorz914** [comment]
Can you try to change language in plugin settings and let me know

**Comment by grzegorz914** [comment]
"language": “0” is correct,  string not number
