### ISSUE TITLE
Unlock physical controls

### ISSUE THREAD

**Issue by imloic** [grzegorz914/homebridge-melcloud-control#58]
Hi, 

How to unlock physical controls, please ? I can't use my physique remote controller. thanks

**Comment by grzegorz914** [comment]
If you have any trouble just use MELCloud app

**Comment by imloic** [comment]
Yes I use. But I cannot use my remote now. In  homebridge lock status is to 1. I try to change to 0

**Comment by grzegorz914** [comment]
You can always unlock it using MELCloud app, if no may be you have no communication to AC device.

**Comment by imloic** [comment]
I found the problem. Some options in Melcloud app lock the remote. This app is not updated and is old…working not so well with the last mitshubishi models.

**Comment by grzegorz914** [comment]
The issue was fixed some weeks before.
