### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by cars11** [grzegorz914/homebridge-melcloud-control#60]
Home bridge log says Air Conditioner Bedroom check device state error, AxiosError: Req uest failed with status code 401, check again in 60s.

I have not changed anything. It does work for a while if I restart my homebridge server.

but then next time I try maybe a day later that error again

**Comment by tjsousa** [comment]
Also seeing the same error on my side, Melcloud app for iOS authenticates and loads without any issue.

**Comment by grzegorz914** [comment]
May be just restart the child bridge.

**Comment by cars11** [comment]
I reinstalled everything and the issue persists, however it occurs a lot less now

**Comment by grzegorz914** [comment]
This issue not corresponded direct to plugin rather to server side, so right now I close this.
