### ISSUE TITLE
3 Mitsubishi units available through MELCoud but only 1 visible in Homekit

### ISSUE THREAD

**Issue by ionutm80** [grzegorz914/homebridge-melcloud-control#61]
Hi, as the title says I have 3 Mitsubishi HVAC units available in MELCloud: HVAC-Dorm.Mici, HVAC-Dorm.Matrim. and HVAC-Mansarda, and discoverable by the homebridge plugin however only 1 is visible to Homekit: HVAC-Mansarda, and I can pair it. Do you have any idea what am I doing wrong? I have attached a notepad file with the plugin logs and a printscreen from Homekit where it only shows the bridge and 1 HAVC units as visible.
[homebridge-melcloud log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/13758911/homebridge-melcloud.log.txt)
![19575](https://github.com/grzegorz914/homebridge-melcloud-control/assets/68031938/dd97bcfa-da29-4d4c-810a-3efd01ab5bce)

**Comment by grzegorz914** [comment]
Try to add home bridge-melcloud-control bridge

**Comment by grzegorz914** [comment]
You van also try to change the name of the not visible 2 units

**Comment by ionutm80** [comment]
> Try to add home bridge-melcloud-control bridge

Hi, already done that. No change, still only one unit visible.
![46828](https://github.com/grzegorz914/homebridge-melcloud-control/assets/68031938/776c9666-e9f2-4f44-bffc-a9e89a29b43a)

**Comment by ionutm80** [comment]
> You can also try to change the name of the not visible 2 units

Where can I do that?

**Comment by grzegorz914** [comment]
The name can be changed in MelCLOUD service

**Comment by grzegorz914** [comment]
Please also enable debug mode in plugin settings Advanced Settings>>>System>>Debug and get the whole log.

**Comment by ionutm80** [comment]
> The name can be changed in MelCLOUD service

Solve it, after renaming the units without dots in their name, went from HVAC-Dorm.Mici to HVAC-DormMici

Thanks!
