### ISSUE TITLE
VaneVerticalDirection split

### ISSUE THREAD

**Issue by xophr** [grzegorz914/homebridge-melcloud-control#62]
Would it be possible to add indepebdent "VaneVerticalDirection" into your melcloud integration? This would allow, as per the physical remote, to direct air from left/right vane to different vertical positions, eg upper/lower floor.

Despite Melcloud (app) seemingly not supporting this, I've seen some discussions of it eg here:

https://github.com/Black-Thunder/ioBroker.melcloud/issues/24

".. I've been observing the VaneVerticalDirection and VaneHorizontalDirection in the ListDevices endpoint directly to verify my assumptions."

The HA implementation also seems to allow for it:
https://www.home-assistant.io/integrations/melcloud/

![image](https://github.com/grzegorz914/homebridge-melcloud-control/assets/126240527/d9098e49-ac18-472c-a200-b5cab87e41b3)

Have you already looked into this?

Thanks in advance!

**Comment by grzegorz914** [comment]
Hi, I think this is not possible right now because original MelCloud app do not contain this possibility too.

**Comment by xophr** [comment]
The HA implementation is based on pymelcloud, and you might be correct. Although the vertical vane split is mentioned on the front page (previous screenshot), I can only find references to "split” under horizontal vane direction, when looking through eg ata_device.py.

![image](https://github.com/grzegorz914/homebridge-melcloud-control/assets/126240527/62cc2500-2435-44e8-9644-a703b8d304a9)

[https://github.com/vilppuvuorinen/pymelcloud/tree/master/pymelcloud](url)

Perhaps the original developer might be able to shed some light on this?

Thanks for looking into this nonetheless! (And for bringing support to homebridge, much appreciated.)

**Comment by grzegorz914** [comment]
please try 0.14.0-beta.1 and let me know, I have added this mode in buttons section

**Comment by grzegorz914** [comment]
Added in 0.14.0
