### ISSUE TITLE
It does not override the air conditioning

### ISSUE THREAD

**Issue by starec007** [grzegorz914/homebridge-melcloud-control#64]
The plugin doesn't work for me for about 3 days. I can see the air conditioner in the homebridge accessory and can control it, but it won't transfer to my Apple home. I have been using this plugin for a long time and it has always worked. I do not know where is the problem.

**Comment by grzegorz914** [comment]
What do you do before, are you updated something in your system?

**Comment by starec007** [comment]
I updated the Homebridge UI, but I had a problem with restarting Homebridge, so I reverted to the previous version. It hasn't been possible since then. I also tried deleting the Mel cloud plugin and setting it up again, but it didn't help.

**Comment by grzegorz914** [comment]
HB UI 4.55.1 contain bud, which is fixed in 4.55.2-beta. Try to update to this version. First remove plugin from Home.aa and home bridge, clear HB cashes, install new UI then try install plugin again

**Comment by starec007** [comment]
I did as you wrote, but it didn't help. I still only see air conditioning in the Homebridge extravagance. It was not transferred to my apple home.

**Comment by grzegorz914** [comment]
This will not be automatically transferred, you need add it from Jome app.

**Comment by starec007** [comment]
I never had to add manually. Every accessory was added automatically. When I add accessories, apple home can't find anything for me.

**Comment by starec007** [comment]
[homebridge-melcloud-control.log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/13875027/homebridge-melcloud-control.log.txt)

**Comment by starec007** [comment]
I have version v0.14.4 installed. I enabled debugging in the settings.

**Comment by grzegorz914** [comment]
Homebridge UI X?

**Comment by starec007** [comment]
Just like you wrote to me v4.55.2beta

**Comment by grzegorz914** [comment]
Debug my plugins can be only enabled in plugin settings not in Homebridge settings.

**Comment by grzegorz914** [comment]
Please get the correct debug, because child bridge crashes and indont know why.

**Comment by starec007** [comment]
I have child bridge turned off. It didn't work for me even when I added it

**Comment by starec007** [comment]
I have enabled in the plugin settings

**Comment by grzegorz914** [comment]
I need the debug to check correct publish process, can you post config.joson.

**Comment by starec007** [comment]
How do I get the config.joson?

**Comment by starec007** [comment]
[09/01/2024, 16:09:37] [melcloudcontrol] Account Domov, debug: Found: 1 devices.
[09/01/2024, 16:10:05] [melcloudcontrol] Air Conditioner, Domov, debug: Info: {
  "DeviceID": 133383,
  "DeviceName": "Domov",
  "BuildingID": 76246,
  "BuildingName": null,
  "FloorID": null,
  "FloorName": null,
  "AreaID": null,
  "AreaName": null,
  "ImageID": 41482,
  "InstallationDate": "2018-03-31T00:00:00",
  "LastServiceDate": "2018-03-31T00:00:00",
  "Presets": [
    {
      "SetTemperature": 25,
      "Power": true,
      "OperationMode": 1,
      "VaneHorizontal": 3,
      "VaneVertical": 7,
      "FanSpeed": 0,
      "ID": 55787,
      "Client": 108468,
      "DeviceLocation": 133383,
      "Number": 1,
      "Configuration": "<settings><st>25</st><pw>true</pw><om>1</om><vd>7</vd><hd>3</hd><fs>0</fs></settings>",
      "NumberDescription": "Kurenie"
    },
    {
      "SetTemperature": 25,
      "Power": true,
      "OperationMode": 3,
      "VaneHorizontal": 0,
      "VaneVertical": 1,
      "FanSpeed": 0,
      "ID": 67691,
      "Client": 108468,
      "DeviceLocation": 133383,
      "Number": 2,
      "Configuration": "<settings><st>25</st><pw>true</pw><om>3</om><vd>1</vd><hd>0</hd><fs>0</fs></settings>",
      "NumberDescription": "Chladenie"
    },
    {
      "SetTemperature": 26,
      "Power": true,
      "OperationMode": 1,
      "VaneHorizontal": 3,
      "VaneVertical": 7,
      "FanSpeed": 3,
      "ID": 137080,
      "Client": 108468,
      "DeviceLocation": 133383,
      "Number": 3,
      "Configuration": "<settings><st>26</st><pw>true</pw><om>1</om><vd>7</vd><hd>3</hd><fs>3</fs></settings>",
      "NumberDescription": "Kurenie 2"
    }
  ],
  "OwnerID": null,
  "OwnerName": null,
  "OwnerEmail": null,
  "AccessLevel": 4,
  "DirectAccess": false,
  "EndDate": "2500-01-01T00:00:00",
  "Zone1Name": null,
  "Zone2Name": null,
  "MinTemperature": 0,
  "MaxTemperature": 40,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "HideRoomTemperature": false,
  "HideSupplyTemperature": false,
  "HideOutdoorTemperature": false,
  "EstimateAtaEnergyProductionOptIn": false,
  "EstimateAtaEnergyProduction": false,
  "BuildingCountry": null,
  "OwnerCountry": null,
  "AdaptorType": -1,
  "LinkedDevice": null,
  "Type": 0,
  "MacAddress": "a0:c9:a0:0b:b6:6a",
  "SerialNumber": "1802263148",
  "Device": {
    "PCycleActual": 0,
    "ErrorMessages": "",
    "DeviceType": 0,
    "CanCool": true,
    "CanHeat": true,
    "CanDry": true,
    "CanAuto": false,
    "HasAutomaticFanSpeed": true,
    "AirDirectionFunction": true,
    "SwingFunction": true,
    "NumberOfFanSpeeds": 5,
    "UseTemperatureA": true,
    "TemperatureIncrementOverride": 0,
    "TemperatureIncrement": 0.5,
    "MinTempCoolDry": 16,
    "MaxTempCoolDry": 31,
    "MinTempHeat": 10,
    "MaxTempHeat": 31,
    "MinTempAutomatic": 16,
    "MaxTempAutomatic": 31,
    "LegacyDevice": false,
    "UnitSupportsStandbyMode": true,
    "IsSplitSystem": false,
    "HasHalfDegreeIncrements": false,
    "HasOutdoorTemperature": false,
    "ModelIsAirCurtain": false,
    "ModelSupportsFanSpeed": true,
    "ModelSupportsAuto": true,
    "ModelSupportsHeat": true,
    "ModelSupportsDry": true,
    "ModelSupportsVaneVertical": true,
    "ModelSupportsVaneHorizontal": true,
    "ModelSupportsWideVane": false,
    "ModelDisableEnergyReport": false,
    "ModelSupportsStandbyMode": true,
    "ModelSupportsEnergyReporting": false,
    "ProhibitSetTemperature": false,
    "ProhibitOperationMode": false,
    "ProhibitPower": false,
    "Power": false,
    "RoomTemperature": 26,
    "OutdoorTemperature": null,
    "SetTemperature": 26.5,
    "ActualFanSpeed": 0,
    "FanSpeed": 3,
    "AutomaticFanSpeed": false,
    "VaneVerticalDirection": 7,
    "VaneVerticalSwing": true,
    "VaneHorizontalDirection": 3,
    "VaneHorizontalSwing": false,
    "OperationMode": 1,
    "EffectiveFlags": 0,
    "LastEffectiveFlags": 0,
    "InStandbyMode": false,
    "DemandPercentage": 100,
    "ConfiguredDemandPercentage": null,
    "HasDemandSideControl": false,
    "DefaultCoolingSetTemperature": 21,
    "DefaultHeatingSetTemperature": 23,
    "RoomTemperatureLabel": 0,
    "HeatingEnergyConsumedRate1": 0,
    "HeatingEnergyConsumedRate2": 0,
    "CoolingEnergyConsumedRate1": 0,
    "CoolingEnergyConsumedRate2": 0,
    "AutoEnergyConsumedRate1": 0,
    "AutoEnergyConsumedRate2": 0,
    "DryEnergyConsumedRate1": 0,
    "DryEnergyConsumedRate2": 0,
    "FanEnergyConsumedRate1": 0,
    "FanEnergyConsumedRate2": 0,
    "OtherEnergyConsumedRate1": 0,
    "OtherEnergyConsumedRate2": 0,
    "EstimateAtaEnergyProduction": false,
    "EstimateAtaEnergyProductionOptIn": false,
    "EstimateAtaEnergyProductionOptInTimestamp": null,
    "WeatherForecast": [],
    "HasEnergyConsumedMeter": false,
    "CurrentEnergyConsumed": 0,
    "CurrentEnergyMode": 1,
    "CoolingDisabled": false,
    "EnergyCorrectionModel": null,
    "EnergyCorrectionActive": false,
    "MinPcycle": 1,
    "MaxPcycle": 1,
    "EffectivePCycle": 1,
    "MaxOutdoorUnits": 255,
    "MaxIndoorUnits": 255,
    "MaxTemperatureControlUnits": 0,
    "ModelCode": "0130",
    "DeviceID": 133383,
    "MacAddress": "a0:c9:a0:0b:b6:6a",
    "SerialNumber": "1802263148",
    "TimeZoneID": 120,
    "DiagnosticMode": 0,
    "DiagnosticEndDate": null,
    "ExpectedCommand": 1,
    "Owner": null,
    "DetectedCountry": null,
    "AdaptorType": -1,
    "FirmwareDeployment": null,
    "FirmwareUpdateAborted": false,
    "LinkedDevice": null,
    "WifiSignalStrength": -34,
    "WifiAdapterStatus": "NORMAL",
    "Position": "Unknown",
    "PCycle": 10,
    "PCycleConfigured": null,
    "RecordNumMax": 0,
    "LastTimeStamp": "2024-01-09T16:08:00",
    "ErrorCode": 8000,
    "HasError": false,
    "LastReset": "2022-03-31T18:11:45.546",
    "FlashWrites": 2,
    "Scene": null,
    "SSLExpirationDate": "2037-12-31T00:00:00",
    "SPTimeout": 1,
    "Passcode": null,
    "ServerCommunicationDisabled": false,
    "ConsecutiveUploadErrors": 0,
    "DoNotRespondAfter": null,
    "OwnerRoleAccessLevel": 1,
    "OwnerCountry": 204,
    "HideEnergyReport": false,
    "ExceptionHash": null,
    "ExceptionDate": null,
    "ExceptionCount": null,
    "Rate1StartTime": null,
    "Rate2StartTime": null,
    "ProtocolVersion": 0,
    "UnitVersion": 0,
    "FirmwareAppVersion": 19000,
    "FirmwareWebVersion": 0,
    "FirmwareWlanVersion": 0,
    "LinkToMELCloudHome": false,
    "LinkedByUserFromMELCloudHome": "00000000-0000-0000-0000-000000000000",
    "MqttFlags": 9,
    "HasErrorMessages": false,
    "HasZone2": false,
    "Offline": false,
    "SupportsHourlyEnergyReport": true,
    "Units": [
      {
        "ID": 1,
        "Device": 0,
        "SerialNumber": "7011021 T",
        "ModelNumber": 115,
        "Model": "MUZ-SF50VE(H)",
        "UnitType": 0,
        "IsIndoor": false
      },
      {
        "ID": 2,
        "Device": 0,
        "SerialNumber": "7021177 T",
        "ModelNumber": 580,
        "Model": "MSZ-SF50VE3",
        "UnitType": 1,
        "IsIndoor": true
      }
    ]
  },
  "DiagnosticMode": 0,
  "DiagnosticEndDate": null,
  "Location": 25937,
  "DetectedCountry": null,
  "Registrations": 981,
  "LocalIPAddress": null,
  "TimeZone": 120,
  "RegistReason": "CONFIG",
  "ExpectedCommand": 1,
  "RegistRetry": 0,
  "DateCreated": "2018-11-02T14:25:40.557Z",
  "FirmwareDeployment": null,
  "FirmwareUpdateAborted": false,
  "Permissions": {
    "CanSetOperationMode": true,
    "CanSetFanSpeed": true,
    "CanSetVaneDirection": true,
    "CanSetPower": true,
    "CanSetTemperatureIncrementOverride": true,
    "CanDisableLocalController": true,
    "CanSetDemandSideControl": false
  }
}
[09/01/2024, 16:10:06] [melcloudcontrol] Air Conditioner, Domov, debug: State: {
  "EffectiveFlags": 0,
  "LocalIPAddress": null,
  "RoomTemperature": 26,
  "SetTemperature": 26.5,
  "SetFanSpeed": 3,
  "OperationMode": 1,
  "VaneHorizontal": 3,
  "VaneVertical": 7,
  "Name": null,
  "NumberOfFanSpeeds": 5,
  "WeatherObservations": [
    {
      "Date": "2024-01-09T15:00:00",
      "Sunrise": "2024-01-09T07:41:00",
      "Sunset": "2024-01-09T16:16:00",
      "Condition": 113,
      "ID": 1445081375,
      "Humidity": 44,
      "Temperature": -1,
      "Icon": "wsymbol_0001_sunny",
      "ConditionName": "Jasno/slunečno",
      "Day": 2,
      "WeatherType": 0
    },
    {
      "Date": "2024-01-10T03:00:00",
      "Sunrise": "2024-01-10T07:40:00",
      "Sunset": "2024-01-10T16:17:00",
      "Condition": 113,
      "ID": 1446344883,
      "Humidity": 59,
      "Temperature": -4,
      "Icon": "wsymbol_0008_clear_sky_night",
      "ConditionName": "Jasno/slunečno",
      "Day": 2,
      "WeatherType": 2
    },
    {
      "Date": "2024-01-10T15:00:00",
      "Sunrise": "2024-01-10T07:40:00",
      "Sunset": "2024-01-10T16:17:00",
      "Condition": 113,
      "ID": 1446344887,
      "Humidity": 60,
      "Temperature": 0,
      "Icon": "wsymbol_0001_sunny",
      "ConditionName": "Jasno/slunečno",
      "Day": 3,
      "WeatherType": 1
    },
    {
      "Date": "2024-01-11T03:00:00",
      "Sunrise": "2024-01-11T07:40:00",
      "Sunset": "2024-01-11T16:18:00",
      "Condition": 113,
      "ID": 1447612115,
      "Humidity": 84,
      "Temperature": -4,
      "Icon": "wsymbol_0008_clear_sky_night",
      "ConditionName": "Jasno/slunečno",
      "Day": 3,
      "WeatherType": 2
    }
  ],
  "ErrorMessage": null,
  "ErrorCode": 8000,
  "DefaultHeatingSetTemperature": 23,
  "DefaultCoolingSetTemperature": 21,
  "HideVaneControls": false,
  "HideDryModeControl": false,
  "RoomTemperatureLabel": 0,
  "InStandbyMode": false,
  "TemperatureIncrementOverride": 0,
  "ProhibitSetTemperature": false,
  "ProhibitOperationMode": false,
  "ProhibitPower": false,
  "DemandPercentage": 100,
  "DeviceID": 133383,
  "DeviceType": 0,
  "LastCommunication": "2024-01-09T15:09:41.976",
  "NextCommunication": "2024-01-09T15:10:41.976",
  "Power": false,
  "HasPendingCommand": false,
  "Offline": false,
  "Scene": null,
  "SceneOwner": null

**Comment by grzegorz914** [comment]
Just copy from config ui x

**Comment by starec007** [comment]
Is this it?

**Comment by grzegorz914** [comment]
Yes, this is debug, post the whole debug direct after restart bridge

**Comment by starec007** [comment]
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/13875497/homebridge.log.txt)

**Comment by starec007** [comment]
Is this enough?

**Comment by grzegorz914** [comment]
All is correct here:
`[09/01/2024, 15:31:02] [melcloudcontrol] Domov, Air Conditioner Domov, published as external accessory.
[09/01/2024, 15:31:02] Domov 7DE4 is running on port 44173.
[09/01/2024, 15:31:02] Please add [Domov 7DE4] manually in Home app. Setup Code: 505-41-102 `

just add it to the home app

**Comment by starec007** [comment]
How do I add to apple home? Always added automatically by nmi. I can't add anything.

**Comment by starec007** [comment]
After entering the code, it does not find any accessories for me

**Comment by starec007** [comment]
It doesn't help even if I add a child bridge

**Comment by starec007** [comment]
Everything has worked for me so far. I have been using your plugin for a long time. I never added anything, but after setting up the plugin, the air conditioner was immediately rewritten to apple home.

**Comment by grzegorz914** [comment]
Are you using this procedure https://github.com/grzegorz914/homebridge-melcloud-control/wiki#adding-to-homekit

**Comment by starec007** [comment]
I know how to add accessories. It's not the first time I've done it. But as I already wrote, I don't see any accessories. That's why I can't add it.

**Comment by grzegorz914** [comment]
May be try to change its name in melcloud

**Comment by starec007** [comment]
I changed the name and it didn't help. Still can't add. When I enter the code, it doesn't find anything.

**Comment by starec007** [comment]
Well, it finally works. I tried deleting the entire homebridge. I deleted and reset everything. I installed the plugin and then added the device to Apple home and now it works. I don't know where the problem was, but it is already solved. Hopefully it won't fall out again.

**Comment by grzegorz914** [comment]
Probably still exist old caches.

**Comment by starec007** [comment]
The main thing is that it already works. Thanks for your time

**Comment by grzegorz914** [comment]
nice, have fun 👍
