### ISSUE TITLE
Not an issue, just an idea. 

### ISSUE THREAD

**Issue by Jeepmg** [grzegorz914/homebridge-melcloud-control#66]
Hello, I am thinking about centralizing the different heating systems in homekit.
All these systems have an "eco" mode and a "comfort" mode which does not exist in Melcloud.
Couldn't we consider simulating these 2 modes for the heating mode? For example an “eco” mode which reduces the heating by 3 degrees.

I leave this idea for your consideration.

**Comment by grzegorz914** [comment]
You can just create Automation or scene in Home app for simulate this functions.
