### ISSUE TITLE
Help Please ! Assecsories don't mount in HomeKit

### ISSUE THREAD

**Issue by winross** [grzegorz914/homebridge-melcloud-control#67]
Hi all, i have recently add the melcloudcontrol plugin v0.14.5 in Homebridge and add my air conditioners with her presets in my homekit but after 1 hour : i had to stop and delete the plugin in my homebridge main console because air conditioners were not working properly (they stopped after 5 minutes in use ...) I have delete air conditionners in my Home App too.

Now i want to reinstall and reconfigure step by step the last melcontrol plugin in order : 
1) i re-install Melcloudcontrol plugin in homebridge
2) All air conditioners was discoverd and appear in homebridge accessories page
3) I Reboot Homebridge
4) On my iPhone : i enter the Homebridge QR code in the Apple House App
5) Problem : Apple say i have already this bridge in my House but no new accessories founded ! aircondtioners wasn't discovered in HomeKit !

Can you help me guys please :)

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-melcloud-control/wiki#troubleshooting

**Comment by winross** [comment]
Thank you Sir :)
