### ISSUE TITLE
MELCloud account blocked due to “excessive traffic”

### ISSUE THREAD

**Issue by ianchuter** [grzegorz914/homebridge-melcloud-control#69]
I tried to turn on the AC tonight in the MELCloud app to be greeted with the message:
“We have detected excessive traffic from your account, your access to the service has been limited for a few hours.”

Seeing as I only use the app once or twice a day I’m guessing this has been triggered by the homebridge plugin… 

Anyone else started seeing this?

**Comment by nifoc** [comment]
Sorry for what is essentially a +1 comment, but I'm seeing the same thing.

I came to the same conclusion, because I use the actual MELCloud Website/"App" maybe once per week.

**Comment by tobuser** [comment]
Request failed with status code 429, check again in 60s.

Same :-(

**Comment by ssarl** [comment]
Same here.

**Comment by grzegorz914** [comment]
Please read #68
