### ISSUE TITLE
MQTT Publish error: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer.

### ISSUE THREAD

**Issue by Jeepmg** [grzegorz914/homebridge-melcloud-control#7]
When I enable MQTT option I get the message error :

MQTT Publish error: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object

I try to change MQTT prefix but what I have done I got same error message.

I use a 2.10 mosquitto server with zigbee2mqtt and  Homebridge Zigbee2MQTT plugin.

**Comment by grzegorz914** [comment]
Will be fixed in the next release.
