### ISSUE TITLE
Log out problem

### ISSUE THREAD

**Issue by starec007** [grzegorz914/homebridge-melcloud-control#73]
After the last updates, the MELcloud application does not work for me. I have the longest refresh times set but it doesn't help.
The application writes this:
We have detected excessive traffic from your account, your access to the service has been limited for a few hours.

**Comment by easyproger** [comment]
same for me, yesterday i disabled plugin and today melcloud site work, but im scary enable plugin in homebridge, I think we need wait answer from developer

**Comment by starec007** [comment]
I also disabled the plugin, but the problem started again after a while.

**Comment by easyproger** [comment]
go to another topic - https://github.com/grzegorz914/homebridge-melcloud-control/issues/68 here discussion about this problem

**Comment by grzegorz914** [comment]
same case already exist #68
