### ISSUE TITLE
Some devices don't find (No device found.)

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#77]
Now i have noch problem with the acoount refresh (250s).

But from my devices only 1 from 2 climate device found. Also the heatpump is found. But 2 from 2 Lossnays devices are not found. I try to install a fresh installation but the problem is the same.

The last 4 month i have no problem. The last version without a problem was 14.5

**Comment by grzegorz914** [comment]
#68

**Comment by grzegorz914** [comment]
fixed in beta.38
