### ISSUE TITLE
No devices. Units are not configured in MELCloud service. Errors in log 

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#78]
I install a new homebridge server with proxmox homebridge script. After config my account and start the plugin i get error messages and the plugin stop and restart in a loop.

No devices. Units are not configured in MELCloud service. Errors in log 
[homebridge.log (3).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14259196/homebridge.log.3.txt)

**Comment by grzegorz914** [comment]
`No devices. Units are not configured in MELCloud service.`

This is just info that You don't have configured Your units in MELCLoud Service. 
Error was fixed with 0.16.1

**Comment by tobuser** [comment]
Thanx. All my devices are working. :-)
