### ISSUE TITLE
Air Conditioner Klimaanlage Units are not configured in MELCloud service

### ISSUE THREAD

**Issue by MorreMor** [grzegorz914/homebridge-melcloud-control#79]
Hi, can't find any devices. the fail is Air Conditioner Klimaanlage Units are not configured in MELCloud service.
what should I do?

**Comment by grzegorz914** [comment]
Nothing, it's just info.  Her is how to ad it: https://github.com/grzegorz914/homebridge-melcloud-control/wiki#adding-to-homekit

If You don see this devices to add it then please post the debug log, enable it in plugin config advanced settings>> system>>>debug.

**Comment by MorreMor** [comment]
works
