### ISSUE TITLE
Add ascenes configured in melcloud to Homekit

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#84]
First of all, thank you for your job. It's a great and essential plugin for me.
If it is posible, I'm very proud if you add to the plugin the function to add scenes (not presets) configured in melcloud to Homekit. I don't know if is technically posible, but if its, this function will made configure scenes and shortcust easiest. Thank you.

**Comment by grzegorz914** [comment]
Unfortunately the scenes are not available through api, but You can easy create scenes in Home app.
