### ISSUE TITLE
Units are not configured in MELCloud service

### ISSUE THREAD

**Issue by Lechucico** [grzegorz914/homebridge-melcloud-control#86]
Since 0.16.16 - 0.16.0 there's a lot of logs that appear repeatedly:

![image](https://github.com/grzegorz914/homebridge-melcloud-control/assets/22009615/f4f8d1b1-b3ec-4ac6-ba40-b6037961fd27)

My units are already paired on HomeKit, I don't get what I'm missing.

**Comment by grzegorz914** [comment]
Paired but not configured,if you edit your device in MELCloud app you can also select model and serial number, if this are not set the info just appear. It just info nothing wrong.
