### ISSUE TITLE
mqtt is broken

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#87]
Since Version 16.13 the mqtt messages are broken. I downgrade to test this issue with older version an the last version without mqtt problem was 16.02.

**Comment by grzegorz914** [comment]
What is broken exactly?

**Comment by grzegorz914** [comment]
Yes it is broken, I will fix it in next update.

**Comment by peibol81** [comment]
Sorry, but wat is mqtt and why is important in this plugin?

**Comment by tobuser** [comment]
Its only important when you what send Infos/sensor states to another system. In my case Home Assistant.
https://en.wikipedia.org/wiki/MQTT

**Comment by tobuser** [comment]
With 16.17. the problem with mqtt doesn't change. No mqtt Infos.

**Comment by grzegorz914** [comment]
@tobuser any log, Mqtt debug?

**Comment by tobuser** [comment]
Unfortunately, Melcloud is still very sensitive. The refresh is set to 400s. A reboot seems to access Melcloud too early. I've noticed a change by Melcloud. When Homebridge Melcloud Control reports the error 'Login error: AxiosError: Request failed with status code 429, reconnect in 401s.', I can directly control the devices with the iPhone Melcloud app without any issues. This was not possible some time ago, as both Melcloud Control and the Melcloud app were blocked. It seems that Melcloud is giving preference to the app over Melcloud Control. I will wait until tomorrow and then create the debug files.

**Comment by grzegorz914** [comment]
I have set refresh time to 120sec and will never locked by melcloud server. Are you have other integrations like Home Assistant, etc… with Melcloud?

**Comment by tobuser** [comment]
I removed all Home Assistant integrations last week, but I found now another session of Melcloud Control on a different host that I forgot to stop. Thanks for the tip.
Logs later

**Comment by tobuser** [comment]
Here the log with the mqtt issue.

[homebridge.log (8).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14426420/homebridge.log.8.txt)

**Comment by grzegorz914** [comment]
Try latest beta and get the debug again

**Comment by tobuser** [comment]
[homebridge.log (9).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14430192/homebridge.log.9.txt)

Only one Device "AC Wohnzimmer" publish mqtt

**Comment by grzegorz914** [comment]
try beta 8 and get the log again

**Comment by tobuser** [comment]
The device "AC Wohnzimmer" have now another mqtt topic name. But no other devices with mqtt publish
[homebridge.log (10).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14432038/homebridge.log.10.txt)
<img width="657" alt="Bildschirmfoto 2024-02-28 um 10 58 55" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/24873682/2f19aa12-e694-4a6a-86f6-5f8f90a93546">

**Comment by tobuser** [comment]
also reboot loops
[homebridge.log (11).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14432273/homebridge.log.11.txt)

**Comment by grzegorz914** [comment]
crash fixed in beta.9 also debug please

**Comment by tobuser** [comment]
Test with beta.11. 
For me it looks like all devices now publish in the same topic ha_melcloud_hse/Air Conditioner/Wohnzimmer klima (screenshots)

[homebridge.log (12).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14432882/homebridge.log.12.txt)
<img width="405" alt="Bildschirmfoto 2024-02-28 um 11 58 42" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/24873682/976333fa-f0d2-48fb-b5ac-c0c8c38ca607">
<img width="327" alt="Bildschirmfoto 2024-02-28 um 11 58 12" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/24873682/fe20e88d-dc73-443f-b13e-e30ad8523696">

**Comment by grzegorz914** [comment]
try beta 12

**Comment by tobuser** [comment]
[homebridge.log (13).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14434576/homebridge.log.13.txt)

Reboot loop very often

**Comment by tobuser** [comment]
That looks good. Thank you!
<img width="590" alt="Bildschirmfoto 2024-02-29 um 01 07 04" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/24873682/64591a2d-eedb-4aea-8864-8f7fb30bd934">
