### ISSUE TITLE
Can’t control fan speed

### ISSUE THREAD

**Issue by daniburton1** [grzegorz914/homebridge-melcloud-control#88]
As per title I can only change the temperature and the mode

**Comment by peibol81** [comment]
In my case, the plugin respects the configuration it has on the web and the melcloud app. If the air conditioner is set to 'auto', it stays that way. If it is for example in '3', the same. In my case I always have it set up in melcloud enn'auto' and I haven't touched it and it works well. In this configuration, the air conditioner works at a faster speed when it is turned on as it reaches the requested temperature, it slows down. It's the most efficient configuration mode.

**Comment by daniburton1** [comment]
Me too i prefer using auto mode but it would be better to have the possibility to choose directly in iOS home app

**Comment by grzegorz914** [comment]
@daniburton1 
The fan speed can be direct set per Extra tile or direct in AC Tile Settings with slider.

**Comment by daniburton1** [comment]
Could you explain me further? I haven’t found anything helping

**Comment by grzegorz914** [comment]
Just go to plugin settings and create extra tile with available functions. 
![IMG_0940](https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/a1d493a2-b9ce-47ec-b0ff-41bf5820f680)

**Comment by daniburton1** [comment]
![image](https://github.com/grzegorz914/homebridge-melcloud-control/assets/160672437/9dc409a6-29a9-4894-8df2-9b76eed469ef)


Isn’t something like this possible ?
Took it from another thread

**Comment by grzegorz914** [comment]
You want to have slider?

**Comment by daniburton1** [comment]
it would be useful to have it, for example under the temperature controller. i don't know if you can implement it while giving also the possibility to set the auto fan speed if i don't want to choose a particular manual speed

**Comment by grzegorz914** [comment]
Why you not use this integrated function, here you can set all possible speeds inclusive Auto.
![IMG_1366](https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/eb4107d1-013d-4176-b13a-8de4dcc7ab9c)

**Comment by daniburton1** [comment]
how do i set this up on iOS home ?

Il giorno mar 27 feb 2024 alle ore 10:03 Grzegorz ***@***.***>
ha scritto:

**Comment by grzegorz914** [comment]
![IMG_1367](https://github.com/grzegorz914/homebridge-melcloud-control/assets/28867813/192772a7-cc21-4d81-a70d-f96e65f4c18a)

**Comment by daniburton1** [comment]
https://share.icloud.com/photos/0a7tOrHumJ-yn4AicaOKQ4GYA

Don’t see anything

**Comment by grzegorz914** [comment]
Strange, please post the debug log the I can look  why this is not displayed

**Comment by daniburton1** [comment]
[homebridge-melcloud-control.log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14419505/homebridge-melcloud-control.log.txt)
is that enough? 
i removed home code and mac addresses

**Comment by grzegorz914** [comment]
Do not enable debug in Homebridge, go to plugin config Advanced Settings>>>System>>>Debug, enable it, save restart and get the log.

**Comment by grzegorz914** [comment]
All OK in your log, I don’t have any idea why this additional functions are not displayed in your case. Very strange. Check your Home app, may be some settings lock this functionality.

**Comment by daniburton1** [comment]
![image](https://github.com/grzegorz914/homebridge-melcloud-control/assets/160672437/c2e44673-15f8-40ae-baad-7971a2544550)

are doubled devices a problem? i have them since i installed the bridge

**Comment by daniburton1** [comment]
It works! Thanks!
