### ISSUE TITLE
Default password of melcloud wifi interface

### ISSUE THREAD

**Issue by peibol81** [grzegorz914/homebridge-melcloud-control#89]
What comes next is not a problem of the plugin but I comment on it here because you as melcloud users may know the answer and because I have not found it anywhere else. What is the default username and password of the melcloud Mitsubishi Wi-Fi interface? When I try to access the IP of the climate control with the browser it asks me for a username and password and I have tried the typical and I have never been able to access it. I don't know if it is established at the time of the initial installation or configuration, but if so, the installer technician didn't tell me anything. I've been looking for the answer for 4 years. Thank you

**Comment by grzegorz914** [comment]
The user and password is on the back side of WiFi interface.
