### ISSUE TITLE
'Current Heater-Cooler State': Characteristic not in required or optional characteristic section for service Thermostat. Adding anyway.

### ISSUE THREAD

**Issue by alesf** [grzegorz914/homebridge-melcloud-control#92]
Hi again!

I get this line in the logs as a warning:
'Current Heater-Cooler State': Characteristic not in required or optional characteristic section for service Thermostat. Adding anyway.

**Comment by grzegorz914** [comment]
which device, debug log

**Comment by alesf** [comment]
Heat pump.
Here are the logs (same as in the other issue as the error occurs simultaneously):
https://pastebin.com/tvR6NWUm

**Comment by grzegorz914** [comment]
please try 0.17.1-beta and let me know
