### ISSUE TITLE
Separate thermostats

### ISSUE THREAD

**Issue by alesf** [grzegorz914/homebridge-melcloud-control#93]
Hi!

Would it be possible to separate heat pump thermostats as separate accessories?

I know I can separate them in Home app, but I can't put them into separate rooms.
That way it would be possible to put outdoor unit "outside" so it doesn't interfere with indoor temperatures.

**Comment by grzegorz914** [comment]
The heat pump is one accessory which contain 2 - 4 thermostat services. You can ungroup it but is not possible to assign to separate rooms right now. It is possible to create 4 separate accessory but I don't know if this is god concept.
