### ISSUE TITLE
after upgrading to 0.16.19 the AC's are not responding in Home App

### ISSUE THREAD

**Issue by mpopof** [grzegorz914/homebridge-melcloud-control#94]
I have two issues one is been going on ever since 0.16.x which is the change log is not showing up what the changes are. It always points to 0.16.0 instead of the newer version that is supposed to be installed. 
![Screenshot from 2024-02-29 06-44-06](https://github.com/grzegorz914/homebridge-melcloud-control/assets/47221576/8375d802-5409-4c8a-b094-72fcc4005eb2)
and the other issue now is that when I upgraded to 0.16.19 the ACs are not responding in the Home App.

> [29/02/2024,13:44:38] [homebridge-melcloud-control] Launched child bridge with PID 1018
> [29/02/2024, 13:44:38] Registering platform 'homebridge-melcloud-control.melcloudcontrol'
> [29/02/2024, 13:44:38] [homebridge-melcloud-control] Loaded homebridge-melcloud-control v0.16.19 child bridge successfully
> [29/02/2024, 13:44:38] Loaded 0 cached accessories from cachedAccessories.0E2B4E8C677E.
> [29/02/2024, 13:44:39] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-melcloud-control) is running on port 40906.
> [29/02/2024, 13:44:41] [homebridge-melcloud-control] ---- Air Conditioner: Bedroom ----
> [29/02/2024, 13:44:41] [homebridge-melcloud-control] Account: Slavyanska2
> [29/02/2024, 13:44:41] [homebridge-melcloud-control] Indoor: MUZ-AP25VG
> [29/02/2024, 13:44:41] [homebridge-melcloud-control] Serial: 000000000
> [29/02/2024, 13:44:41] [homebridge-melcloud-control] Firmware: 37000
> [29/02/2024, 13:44:41] [homebridge-melcloud-control] Manufacturer: Mitsubishi
> [29/02/2024, 13:44:41] [homebridge-melcloud-control] ----------------------------------
> [29/02/2024, 13:44:42] [homebridge-melcloud-control] ---- Air Conditioner: Living room  ----
> [29/02/2024, 13:44:42] [homebridge-melcloud-control] Account: Slavyanska2
> [29/02/2024, 13:44:42] [homebridge-melcloud-control] Indoor: MSZ-AP50VG
> [29/02/2024, 13:44:42] [homebridge-melcloud-control] Serial: 000000000
> [29/02/2024, 13:44:42] [homebridge-melcloud-control] Firmware: 37000
> [29/02/2024, 13:44:42] [homebridge-melcloud-control] Manufacturer: Mitsubishi
> [29/02/2024, 13:44:42] [homebridge-melcloud-control] ----------------------------------

This is what i get in the logs. It looks like they (AC's) never load into the system.

**Comment by grzegorz914** [comment]
debug please

**Comment by mpopof** [comment]
Where is the debug file located?

**Comment by mpopof** [comment]
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14451635/homebridge.log.txt)
Here it is

**Comment by grzegorz914** [comment]
fixed
