### ISSUE TITLE
Lossnay Buttons  /Devices missing

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#95]
With Version v0.16.20 my Lossnay Button disapear.

<img width="932" alt="Bildschirmfoto 2024-02-29 um 23 43 54" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/24873682/730f0ba7-1471-4c26-af38-75d65f2c2403">

With Version v0.16.18:
<img width="1592" alt="Bildschirmfoto 2024-02-29 um 09 52 31" src="https://github.com/grzegorz914/homebridge-melcloud-control/assets/24873682/d7c93101-10ad-4d50-8c0c-1d2fee84a395">

**Comment by grzegorz914** [comment]
Please post the debug log

**Comment by tobuser** [comment]
[homebridge.log (15).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14458061/homebridge.log.15.txt)

**Comment by grzegorz914** [comment]
Fixed

**Comment by tobuser** [comment]
No change:
[homebridge.log (16).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14462330/homebridge.log.16.txt)

**Comment by grzegorz914** [comment]
Must be fixed now

**Comment by tobuser** [comment]
Yes, the fix is successful
