### ISSUE TITLE
The Lossnay switching procedure is not correct

### ISSUE THREAD

**Issue by tobuser** [grzegorz914/homebridge-melcloud-control#96]
I have a problem with the Lossnays. When I turn off a Lossnay device, the button becomes grayed out, then after about 1 minute the button turns back on, and only after another minute does the button become grayed out again. This behavior is not noticeable with the air conditioners. Everything is perfect here.
[Uploading homebridge.log (17).txt…]()

**Comment by grzegorz914** [comment]
try 0.18.0-beta and let me know

**Comment by tobuser** [comment]
[homebridge.log (18).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14468642/homebridge.log.18.txt)

The on and off sequence is not working correctly. Unfortunately, I am not at the location where the Lossnays are situated. I can only check the status of the Lossnays using the Melcloud app. It seems that the Lossnays are being switched immediately, but the plugin buttons are switching back. During this process, the Lossnays are not being switched. After 1-3 minutes, the status of the button is corrected again. I hope my description is understandable.

**Comment by grzegorz914** [comment]
Please  first remove old log instance because is very big now, (trash button in config ui x). 
Install beta.2, save and restart plugin, set power off your lossnay with Home app, wait 3 min and get the log please.

**Comment by tobuser** [comment]
[homebridge.log (19).txt](https://github.com/grzegorz914/homebridge-melcloud-control/files/14468832/homebridge.log.19.txt)

Sorry i can't get the Home App working because the app don't find the Bridge on the remote site. But i can activate the Home Integration von Home Assistant. Here i activate the Lossnay wait 3 Minutes. Then i deactivate the Lossnay and wait 3 minutes. And now it seems that the on and off sequence is working correctly!
